using System.Collections.Immutable;
using System.Text;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Inquiry.Generators.Features.Stores;

internal static class StoreImplementationGenerator
{
    public static StoreRegistrationModel Generate(SourceProductionContext context, INamedTypeSymbol storeSymbol, EntityModel entity, ImmutableArray<StoreMethodModel> methods)
    {
        var generatedName = $"Generated{storeSymbol.Name}";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, storeSymbol);
        source.AppendLine($"{GeneratorHelpers.GetAccessibility(storeSymbol.DeclaredAccessibility)} sealed class {generatedName} : {storeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
        source.AppendLine("{");
        source.AppendLine("    private readonly global::Inquiry.Sql.InquirySqlStatementSet _sqlStatements;");
        source.AppendLine();
        source.AppendLine($"    public {generatedName}(global::Inquiry.IInquiry inquiry, global::Inquiry.Sql.InquirySqlDialect sqlDialect)");
        source.AppendLine("        : base(inquiry)");
        source.AppendLine("    {");
        source.AppendLine("        if (sqlDialect is null)");
        source.AppendLine("        {");
        source.AppendLine("            throw new global::System.ArgumentNullException(nameof(sqlDialect));");
        source.AppendLine("        }");
        source.AppendLine();
        source.AppendLine("        _sqlStatements = new global::Inquiry.Sql.InquirySqlStatementBuilder(sqlDialect).Build(");
        source.AppendLine($"            {GeneratorHelpers.Literal(entity.Schema)},");
        source.AppendLine($"            \"{GeneratorHelpers.Escape(entity.TableName)}\",");
        source.AppendLine("            new global::Inquiry.Sql.InquirySqlColumn[]");
        source.AppendLine("            {");
        foreach (var column in entity.Columns)
        {
            source.AppendLine($"                new global::Inquiry.Sql.InquirySqlColumn(\"{GeneratorHelpers.Escape(column.PropertyName)}\", \"{GeneratorHelpers.Escape(column.ColumnName)}\", isKey: {GeneratorHelpers.BooleanLiteral(column.IsKey)}, isGenerated: {GeneratorHelpers.BooleanLiteral(column.IsGenerated)}),");
        }

        source.AppendLine("            });");
        source.AppendLine("    }");
        source.AppendLine();

        foreach (var method in methods)
        {
            method.Feature.GenerateMethod(source, method, entity);
            source.AppendLine();
        }

        source.AppendLine("}");
        GeneratorHelpers.AppendNamespaceEnd(source, storeSymbol);

        context.AddSource($"{storeSymbol.Name}.InquiryStore.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new StoreRegistrationModel(storeSymbol, generatedName);
    }
}
