using System.Data;
using System.Data.Common;
using Inquiry.Connections;
using Inquiry.PostgreSql.Tests.Fixtures;
using Inquiry.Testing;
using Npgsql;
using Respawn;
using Respawn.Graph;

namespace Inquiry.PostgreSql.Tests;

[Collection(PostgreSqlCollection.Name)]
public sealed class InquiryRespawnerTests(PostgreSqlContainerFixture fixture)
{
    private const string Ddl = """
        CREATE TABLE parent (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
        CREATE TABLE child (id INTEGER PRIMARY KEY, parent_id INTEGER REFERENCES parent(id));
        CREATE TABLE lookup (id INTEGER PRIMARY KEY);
        INSERT INTO lookup VALUES (7);
        """;

    private static RespawnerOptions Options => new()
    {
        DbAdapter = DbAdapter.Postgres,
        SchemasToInclude = ["public"],
        TablesToIgnore = [new Table("public", "lookup")],
        WithReseed = true
    };

    [SkippableTheory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task RepeatedResetDeletesRelatedRowsPreservesIgnoredRowsAndReseeds(bool useFactory)
    {
        Skip.IfNot(fixture.IsAvailable, fixture.SkipReason);
        await using var database = await PostgreSqlTestHarness.CreateFromDdlAsync(fixture.AdminConnectionString, Ddl);
        await using var connection = new NpgsqlConnection(database.ConnectionString);
        await connection.OpenAsync();
        var factory = new RecordingFactory(database.ConnectionString);
        var respawner = useFactory
            ? await InquiryRespawner.CreateAsync(factory, Options)
            : await InquiryRespawner.CreateAsync(connection, Options);
        if (useFactory) await AssertDisposedAsync(factory.LastConnection!);

        for (var iteration = 0; iteration < 2; iteration++)
        {
            Assert.Equal(1, await ScalarAsync(connection, "INSERT INTO parent DEFAULT VALUES RETURNING id"));
            await ExecuteAsync(connection, "INSERT INTO child VALUES (1, 1)");
            if (useFactory)
            {
                await respawner.ResetAsync(factory);
                await AssertDisposedAsync(factory.LastConnection!);
            }
            else
            {
                await respawner.ResetAsync(connection);
            }
            Assert.Equal(ConnectionState.Open, connection.State);
            Assert.Equal(0L, await ScalarAsync(connection, "SELECT count(*) FROM parent"));
            Assert.Equal(0L, await ScalarAsync(connection, "SELECT count(*) FROM child"));
            Assert.Equal(7, await ScalarAsync(connection, "SELECT id FROM lookup"));
        }
        Assert.Equal(useFactory ? 3 : 0, factory.OpenCount);
    }

    [SkippableTheory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task FailedResetPreservesCallerConnectionAndDisposesFactoryConnection(bool useFactory)
    {
        Skip.IfNot(fixture.IsAvailable, fixture.SkipReason);
        await using var database = await PostgreSqlTestHarness.CreateFromDdlAsync(fixture.AdminConnectionString, Ddl);
        await using var connection = new NpgsqlConnection(database.ConnectionString);
        await connection.OpenAsync();
        var respawner = await InquiryRespawner.CreateAsync(connection, Options);
        await ExecuteAsync(connection, "DROP TABLE child");
        var factory = new RecordingFactory(database.ConnectionString);

        await Assert.ThrowsAsync<PostgresException>(() => useFactory
            ? respawner.ResetAsync(factory)
            : respawner.ResetAsync(connection));

        if (useFactory) await AssertDisposedAsync(factory.LastConnection!);
        Assert.Equal(ConnectionState.Open, connection.State);
        Assert.Equal(7, await ScalarAsync(connection, "SELECT id FROM lookup"));
    }

    [SkippableTheory]
    [InlineData(false)]
    [InlineData(true)]
    public async Task FailedGraphCreationPreservesCallerConnectionAndDisposesFactoryConnection(bool useFactory)
    {
        Skip.IfNot(fixture.IsAvailable, fixture.SkipReason);
        await using var database = await PostgreSqlTestHarness.CreateFromDdlAsync(fixture.AdminConnectionString, Ddl);
        await using var connection = new NpgsqlConnection(database.ConnectionString);
        await connection.OpenAsync();
        var factory = new RecordingFactory(database.ConnectionString);
        // SQL Server catalog queries fail on PostgreSQL after the connection has opened.
        var incompatibleOptions = new RespawnerOptions { DbAdapter = DbAdapter.SqlServer };
        await Assert.ThrowsAsync<PostgresException>(() => useFactory
            ? InquiryRespawner.CreateAsync(factory, incompatibleOptions)
            : InquiryRespawner.CreateAsync(connection, incompatibleOptions));

        if (useFactory) await AssertDisposedAsync(factory.LastConnection!);
        Assert.Equal(ConnectionState.Open, connection.State);
        Assert.Equal(7, await ScalarAsync(connection, "SELECT id FROM lookup"));
    }

    [SkippableFact]
    public async Task PreCancellationSkipsBorrowedWorkAndReachesFactoryOpen()
    {
        Skip.IfNot(fixture.IsAvailable, fixture.SkipReason);
        await using var database = await PostgreSqlTestHarness.CreateFromDdlAsync(fixture.AdminConnectionString, Ddl);
        await using var connection = new NpgsqlConnection(database.ConnectionString);
        await connection.OpenAsync();
        var respawner = await InquiryRespawner.CreateAsync(connection, Options);
        await ExecuteAsync(connection, "INSERT INTO parent DEFAULT VALUES");
        using var cancellation = new CancellationTokenSource();
        cancellation.Cancel();
        var token = cancellation.Token;
        var factory = new RecordingFactory(database.ConnectionString);

        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => InquiryRespawner.CreateAsync(connection, Options, token));
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => respawner.ResetAsync(connection, token));
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => InquiryRespawner.CreateAsync(factory, Options, token));
        Assert.Equal(token, factory.LastToken);
        await Assert.ThrowsAnyAsync<OperationCanceledException>(() => respawner.ResetAsync(factory, token));
        Assert.Equal(token, factory.LastToken);
        Assert.Equal(0, factory.OpenCount);
        Assert.Null(factory.LastConnection);
        Assert.Equal(ConnectionState.Open, connection.State);
        Assert.Equal(1L, await ScalarAsync(connection, "SELECT count(*) FROM parent"));
    }

    private static async Task AssertDisposedAsync(NpgsqlConnection connection)
    {
        Assert.Equal(ConnectionState.Closed, connection.State);
        await Assert.ThrowsAsync<ObjectDisposedException>(() => connection.OpenAsync());
    }

    private static async Task<object?> ScalarAsync(NpgsqlConnection connection, string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection);
        return await command.ExecuteScalarAsync();
    }

    private static async Task ExecuteAsync(NpgsqlConnection connection, string sql)
    {
        await using var command = new NpgsqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync();
    }

    private sealed class RecordingFactory(string connectionString) : IInquiryConnectionFactory
    {
        public NpgsqlConnection? LastConnection { get; private set; }
        public CancellationToken LastToken { get; private set; }
        public int OpenCount { get; private set; }

        public async ValueTask<DbConnection> OpenConnectionAsync(CancellationToken cancellationToken = default)
        {
            LastToken = cancellationToken;
            cancellationToken.ThrowIfCancellationRequested();
            var connection = new NpgsqlConnection(connectionString);
            try
            {
                await connection.OpenAsync(cancellationToken);
            }
            catch
            {
                await connection.DisposeAsync();
                throw;
            }
            LastConnection = connection;
            OpenCount++;
            return connection;
        }
    }
}
