using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Inquiry.DependencyInjection;
using Inquiry.Northwind.Stores;
using Inquiry.PostgreSql.DependencyInjection;
using Inquiry.PostgreSql.Tests.Fixtures;
using Inquiry.Transactions;
using Microsoft.Extensions.DependencyInjection;
using Npgsql;

namespace Inquiry.PostgreSql.Tests;

/// <summary>
/// End-to-end PostgreSQL row-level security driven by <c>SetLocalAsync</c>: the transaction-scoped
/// GUC an RLS policy reads with <c>current_setting</c>, proving the database enforces the tenant
/// boundary underneath the application's own filters — and, just as importantly, that the setting
/// cannot escape its transaction onto a pooled connection.
/// </summary>
/// <remarks>
/// Two details make the difference between a real test and a vacuous one.
/// <list type="number">
/// <item>The tests connect as <c>rls_app</c>, a purpose-made NON-superuser role, because a superuser
/// bypasses row-level security outright — and the shared container's admin login (<c>postgres</c>)
/// is a superuser, so running these through the harness's own service provider would see every row
/// no matter what the policy said.</item>
/// <item><c>rls_app</c> also OWNS the table, which is why <c>FORCE ROW LEVEL SECURITY</c> is
/// load-bearing here: plain <c>ENABLE</c> exempts the owner, and the whole suite would pass while
/// enforcing nothing.</item>
/// </list>
/// </remarks>
[Collection(PostgreSqlCollection.Name)]
public sealed class RowLevelSecurityIntegrationTests
{
    private const string TenantSetting = "app.tenant_id";
    private const string AppRole = "rls_app";
    private const string AppPassword = "rls_pw";

    // The role is CLUSTER-wide, not per-database, so creating it is guarded — every test method gets
    // its own throwaway database but they all share the one container.
    private const string RlsDdl = """
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'rls_app') THEN
                CREATE ROLE rls_app LOGIN PASSWORD 'rls_pw';
            END IF;
        END $$;

        CREATE TABLE rls_doc (
            id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            tenant_id TEXT NOT NULL,
            title     TEXT NOT NULL);

        INSERT INTO rls_doc (tenant_id, title) VALUES ('t1', 'Tenant one doc'), ('t2', 'Tenant two doc');

        GRANT USAGE ON SCHEMA public TO rls_app;
        ALTER TABLE rls_doc OWNER TO rls_app;
        ALTER TABLE rls_doc ENABLE ROW LEVEL SECURITY;
        ALTER TABLE rls_doc FORCE ROW LEVEL SECURITY;

        CREATE POLICY rls_doc_tenant ON rls_doc
            USING (tenant_id = current_setting('app.tenant_id', true));
        """;

    private readonly PostgreSqlContainerFixture _fixture;
    public RowLevelSecurityIntegrationTests(PostgreSqlContainerFixture fixture) => _fixture = fixture;

    /// <summary>
    /// Creates the RLS database, then a service provider bound to the unprivileged <c>rls_app</c>
    /// login rather than the harness's superuser one.
    /// </summary>
    private async Task<(PostgreSqlTestHarness Harness, ServiceProvider Services)> CreateAsync()
    {
        var harness = await PostgreSqlTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, RlsDdl, "rls");
        var appConnectionString = new NpgsqlConnectionStringBuilder(harness.ConnectionString)
        {
            Username = AppRole,
            Password = AppPassword,
        }.ToString();

        var services = new ServiceCollection();
        services.AddInquiry(typeof(CustomerStore).Assembly);
        services.AddInquiryPostgreSql(appConnectionString);
        return (harness, services.BuildServiceProvider());
    }

    private static Task<long> VisibleCountAsync(IInquiryTransaction tx)
        => tx.ExecuteScalarAsync<long>($"SELECT COUNT(*) FROM rls_doc");

    private static Task<string> VisibleTitlesAsync(IInquiryTransaction tx)
        => tx.ExecuteScalarAsync<string>($"SELECT COALESCE(string_agg(title, ',' ORDER BY title), '') FROM rls_doc");

    private static Task<string> CurrentSettingAsync(IInquiryTransaction tx)
        => tx.ExecuteScalarAsync<string>($"SELECT COALESCE(current_setting('app.tenant_id', true), '<unset>')");

    [SkippableFact]
    public async Task WithoutTheSessionVariableTheRlsPolicyHidesEveryRow()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        // The negative case is the one that proves the policy is live at all. On a connection where
        // the GUC has never been set it reads as NULL under missing_ok, the comparison is NULL, and
        // no row qualifies — fail-closed. If RLS were bypassed (superuser login, or ENABLE without
        // FORCE) this would return 2.
        await using var tx = await inquiry.BeginTransactionAsync();
        Assert.Equal("<unset>", await CurrentSettingAsync(tx));
        Assert.Equal(0L, await VisibleCountAsync(tx));
    }

    [SkippableFact]
    public async Task SetLocalScopesReadsToTheMatchingTenantWithinTheTransaction()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var tx = await inquiry.BeginTransactionAsync();
        await tx.SetLocalAsync(TenantSetting, "t1");

        Assert.Equal(1L, await VisibleCountAsync(tx));
        Assert.Equal("Tenant one doc", await VisibleTitlesAsync(tx));
    }

    [SkippableFact]
    public async Task ASecondTransactionOnThePooledConnectionSeesOnlyItsOwnTenant()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using (var first = await inquiry.BeginTransactionAsync())
        {
            await first.SetLocalAsync(TenantSetting, "t1");
            Assert.Equal("Tenant one doc", await VisibleTitlesAsync(first));
            await first.CommitAsync();
        }

        // Sequential transactions on a pooled data source almost certainly reuse the same physical
        // connection, which is exactly where a session-wide SET would leak. set_config(..., true)
        // reverts at COMMIT, so the second transaction starts clean and sees only its own tenant.
        await using (var second = await inquiry.BeginTransactionAsync())
        {
            await second.SetLocalAsync(TenantSetting, "t2");
            Assert.Equal("Tenant two doc", await VisibleTitlesAsync(second));
            await second.CommitAsync();
        }
    }

    [SkippableFact]
    public async Task TheSettingDoesNotSurviveIntoTheNextTransaction()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using (var first = await inquiry.BeginTransactionAsync())
        {
            await first.SetLocalAsync(TenantSetting, "t1");
            await first.CommitAsync();
        }

        // No RESET, no DISCARD — the transaction ending is the whole cleanup mechanism.
        await using (var next = await inquiry.BeginTransactionAsync())
        {
            // Observed, not assumed: once a custom GUC has been set anywhere in the session, ending
            // the transaction resets it to its DEFAULT — the empty string — rather than undefining
            // it. So current_setting stops returning NULL and starts returning ''. The tenant value
            // is gone either way, and both states are fail-closed against a `col = current_setting`
            // policy, but a policy that branches on IS NULL would not see what it expects here.
            Assert.Equal(string.Empty, await CurrentSettingAsync(next));
            Assert.Equal(0L, await VisibleCountAsync(next));
        }
    }

    [SkippableFact]
    public async Task RollbackDiscardsTheSettingToo()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using (var rolled = await inquiry.BeginTransactionAsync())
        {
            await rolled.SetLocalAsync(TenantSetting, "t1");
            await rolled.RollbackAsync();
        }

        // Same reset-to-default behaviour as the commit path: the value is discarded, and no row is
        // visible without a fresh SetLocalAsync.
        await using (var next = await inquiry.BeginTransactionAsync())
        {
            Assert.Equal(string.Empty, await CurrentSettingAsync(next));
            Assert.Equal(0L, await VisibleCountAsync(next));
        }
    }

    [SkippableFact]
    public async Task SavepointRollbackRevertsAnInnerSetLocal()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var outer = await inquiry.BeginTransactionAsync();
        await outer.SetLocalAsync(TenantSetting, "t1");
        Assert.Equal("Tenant one doc", await VisibleTitlesAsync(outer));

        await using (var savepoint = await outer.BeginTransactionAsync())
        {
            await savepoint.SetLocalAsync(TenantSetting, "t2");
            Assert.Equal("Tenant two doc", await VisibleTitlesAsync(savepoint));
            await savepoint.RollbackAsync();
        }

        // PostgreSQL treats configuration changes as transactional, so ROLLBACK TO SAVEPOINT restores
        // the value the outer transaction had set. Verified empirically, not assumed — if this ever
        // changes, a nested unit of work could silently leave the outer scope widened.
        Assert.Equal("t1", await CurrentSettingAsync(outer));
        Assert.Equal("Tenant one doc", await VisibleTitlesAsync(outer));
    }

    [SkippableFact]
    public async Task SavepointCommitKeepsTheInnerSetLocal()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var outer = await inquiry.BeginTransactionAsync();
        await outer.SetLocalAsync(TenantSetting, "t1");

        await using (var savepoint = await outer.BeginTransactionAsync())
        {
            await savepoint.SetLocalAsync(TenantSetting, "t2");
            await savepoint.CommitAsync();
        }

        // Releasing the savepoint keeps the inner value — the counterpart to the rollback case, and
        // the reason a nested scope must not be assumed to restore the outer tenant on its own.
        Assert.Equal("t2", await CurrentSettingAsync(outer));
    }

    [SkippableFact]
    public async Task TheDictionaryOverloadSetsEveryEntry()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var tx = await inquiry.BeginTransactionAsync();
        await tx.SetLocalAsync(new Dictionary<string, string>
        {
            [TenantSetting] = "t2",
            ["app.request_id"] = "abc-123",
        });

        Assert.Equal("Tenant two doc", await VisibleTitlesAsync(tx));
        Assert.Equal("abc-123", await tx.ExecuteScalarAsync<string>($"SELECT current_setting('app.request_id', true)"));
    }

    [SkippableTheory]
    [InlineData("")]
    [InlineData("   ")]
    [InlineData("tenant_id")]
    [InlineData("app.tenant-id")]
    [InlineData("1app.tenant_id")]
    [InlineData("app.1tenant_id")]
    [InlineData("app.tenant_id; DROP TABLE rls_doc")]
    // .NET's `$` also matches immediately before a trailing newline, so an anchor pair of ^…$ lets
    // this through to set_config, where the server rejects it and ABORTS the caller's transaction —
    // breaking the "throws before any statement runs" guarantee. \A…\z is what actually pins it.
    [InlineData("app.tenant_id\n")]
    [InlineData("app.tenant_id\r\n")]
    public async Task AnInvalidSettingNameThrowsBeforeAnyStatementRuns(string settingName)
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var tx = await inquiry.BeginTransactionAsync();
        await Assert.ThrowsAsync<ArgumentException>(() => tx.SetLocalAsync(settingName, "t1"));

        // The transaction is still usable, which is what "throws before any statement runs" buys:
        // a rejected name never aborts the caller's unit of work.
        await tx.SetLocalAsync(TenantSetting, "t1");
        Assert.Equal("Tenant one doc", await VisibleTitlesAsync(tx));
    }

    [SkippableFact]
    public async Task AMultiPartSettingNameIsAccepted()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        // PostgreSQL accepts more than two dot-separated components, so the validator must too —
        // rejecting a name the server would have taken is our bug, not the caller's.
        await using var tx = await inquiry.BeginTransactionAsync();
        await tx.SetLocalAsync("myapp.rls.tenant_id", "t2");

        Assert.Equal("t2", await tx.ExecuteScalarAsync<string>($"SELECT current_setting('myapp.rls.tenant_id', true)"));
    }

    [SkippableFact]
    public async Task TheDictionaryOverloadAppliesNothingWhenAnyNameIsInvalid()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var tx = await inquiry.BeginTransactionAsync();
        await Assert.ThrowsAsync<ArgumentException>(() => tx.SetLocalAsync(new Dictionary<string, string>
        {
            [TenantSetting] = "t1",
            ["not a valid name"] = "x",
        }));

        // All-or-nothing: the valid entry that happened to come first must NOT have been applied, or a
        // caller who catches the exception continues against a nondeterministic subset.
        Assert.Equal("<unset>", await CurrentSettingAsync(tx));
        Assert.Equal(0L, await VisibleCountAsync(tx));
    }

    [SkippableFact]
    public async Task TheValueIsBoundAsAParameterNotInterpolated()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        var (harness, services) = await CreateAsync();
        await using var _ = harness;
        await using var provider = services;
        var inquiry = provider.GetRequiredService<IInquiry>();

        await using var tx = await inquiry.BeginTransactionAsync();

        // A value carrying SQL syntax is data, not code: it round-trips verbatim and the table
        // referenced in the injection attempt is untouched.
        const string hostile = "t1'; DROP TABLE rls_doc; --";
        await tx.SetLocalAsync(TenantSetting, hostile);

        Assert.Equal(hostile, await CurrentSettingAsync(tx));
        Assert.Equal(0L, await VisibleCountAsync(tx));
    }
}
