namespace Inquiry.FeatureCatalog.FullText;

/// <summary>
/// Per-dialect DDL for the W9 full-text <c>Article</c> table, including the engine-specific full-text
/// index. PostgreSQL needs no index (a sequential <c>to_tsvector</c> scan is correct for small test data);
/// MySQL requires a <c>FULLTEXT</c> index for <c>MATCH…AGAINST</c>; SQL Server requires a full-text catalog
/// + index AND the optional full-text engine component, so its setup is applied separately and gated.
/// </summary>
public static class FullTextSchema
{
    public const string PostgreSqlDdl = """
        CREATE TABLE Article (Id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title TEXT NOT NULL, Body TEXT NOT NULL);
        """;

    public const string MySqlDdl = """
        CREATE TABLE Article (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(400) NOT NULL, Body TEXT NOT NULL, FULLTEXT KEY ft_article (Title, Body)) ENGINE=InnoDB;
        """;

    // PK constraint is explicitly named so the full-text setup can reference it via KEY INDEX.
    public const string SqlServerDdl = """
        CREATE TABLE Article (Id BIGINT IDENTITY(1,1) CONSTRAINT PK_Article PRIMARY KEY, Title NVARCHAR(400) NOT NULL, Body NVARCHAR(MAX) NOT NULL);
        """;

    // Applied after the table by the SQL Server FTS test, inside a try/catch — if the full-text component
    // is not installed (common in the base Linux container) this throws and the test skips with a reason.
    public const string SqlServerCreateCatalog = "CREATE FULLTEXT CATALOG ft_catalog AS DEFAULT;";
    public const string SqlServerCreateIndex =
        "CREATE FULLTEXT INDEX ON Article (Title, Body) KEY INDEX PK_Article WITH CHANGE_TRACKING = AUTO;";
}
