<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks.Contracts\Inquiry.Benchmarks.Contracts.csproj" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks\Inquiry.Benchmarks.csproj" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks.SqlServer\Inquiry.Benchmarks.SqlServer.csproj" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks.PostgreSql\Inquiry.Benchmarks.PostgreSql.csproj" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks.MySql\Inquiry.Benchmarks.MySql.csproj" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks.MariaDb\Inquiry.Benchmarks.MariaDb.csproj" />
    <ProjectReference Include="..\..\benchmarks\Inquiry.Benchmarks.Oracle\Inquiry.Benchmarks.Oracle.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
