using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using GeneratorTypeInfo = Inquiry.Generators.Models.TypeInfo;

namespace Inquiry.Generators;

/// <summary>
/// Discovers <c>[InquiryTable]</c> entities and emits a materializer per entity.
/// </summary>
internal static class EntityProcessor
{
    public static Dictionary<string, EntityModel> Discover(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax> candidates)
    {
        var entities = new Dictionary<string, EntityModel>();

        foreach (var classDeclaration in candidates)
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            var model = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            if (model.GetDeclaredSymbol(classDeclaration, context.CancellationToken) is not INamedTypeSymbol entitySymbol)
            {
                continue;
            }

            var tableAttribute = GeneratorHelpers.GetEntityAttribute(entitySymbol, "InquiryTableAttribute");
            if (tableAttribute is null)
            {
                continue;
            }

            var tableName = GeneratorHelpers.GetConstructorString(tableAttribute) ?? entitySymbol.Name;
            var schema = GeneratorHelpers.GetNamedString(tableAttribute, "Schema");
            var columns = DiscoverColumns(context, entitySymbol);

            var keyColumns = columns.Where(static c => c.IsKey).ToArray();
            if (keyColumns.Length != 1)
            {
                context.ReportDiagnostic(Diagnostic.Create(InquiryDiagnosticDescriptors.EntityKeyCount, classDeclaration.Identifier.GetLocation(), entitySymbol.Name));
                continue;
            }

            foreach (var duplicate in columns.GroupBy(static c => c.ColumnName, StringComparer.OrdinalIgnoreCase).Where(static g => g.Count() > 1))
            {
                context.ReportDiagnostic(Diagnostic.Create(InquiryDiagnosticDescriptors.DuplicateColumn, classDeclaration.Identifier.GetLocation(), entitySymbol.Name, duplicate.Key));
            }

            var entity = new EntityModel(entitySymbol, tableName, schema, columns, keyColumns[0]);
            entities[entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)] = entity;
        }

        return entities;
    }

    public static EntityRegistrationModel EmitMaterializer(SourceProductionContext context, EntityModel entity)
    {
        var materializerName = $"{entity.Symbol.Name}InquiryEntityMaterializer";
        var entityType = entity.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, entity.Symbol);
        source.AppendLine($"internal sealed class {materializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{entityType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {entityType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        source.AppendLine($"        return new {entityType}");
        source.AppendLine("        {");
        for (var i = 0; i < entity.Columns.Count; i++)
        {
            var column = entity.Columns[i];
            source.AppendLine($"            {column.PropertyName} = {ReadExpression(column.Type, i)},");
        }

        source.AppendLine("        };");
        source.AppendLine("    }");
        source.AppendLine("}");
        GeneratorHelpers.AppendNamespaceEnd(source, entity.Symbol);

        context.AddSource($"{entity.Symbol.Name}.InquiryEntity.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new EntityRegistrationModel(entity.Symbol, materializerName);
    }

    private static List<ColumnModel> DiscoverColumns(SourceProductionContext context, INamedTypeSymbol entitySymbol)
    {
        var columns = new List<ColumnModel>();

        foreach (var property in entitySymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var keyAttribute = GeneratorHelpers.GetEntityAttribute(property, "InquiryKeyAttribute");
            var columnAttribute = keyAttribute ?? GeneratorHelpers.GetEntityAttribute(property, "InquiryColumnAttribute");
            var foreignKeyAttribute = GeneratorHelpers.GetEntityAttribute(property, "InquiryForeignKeyAttribute");
            if (columnAttribute is null && foreignKeyAttribute is null)
            {
                continue;
            }

            var columnName = ResolveColumnName(columnAttribute, foreignKeyAttribute, property.Name);
            var typeInfo = GeneratorTypeInfo.Create(property.Type, property.NullableAnnotation);
            var isGenerated = keyAttribute is not null && GeneratorHelpers.GetNamedBool(keyAttribute, "IsGenerated");
            columns.Add(new ColumnModel(property, property.Name, columnName, typeInfo, keyAttribute is not null, isGenerated));

            if (!typeInfo.IsSupported)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InquiryDiagnosticDescriptors.UnsupportedPropertyType,
                    property.Locations.FirstOrDefault(),
                    entitySymbol.Name,
                    property.Name,
                    property.Type.ToDisplayString()));
            }

            if (property.SetMethod is null || property.SetMethod.DeclaredAccessibility == Accessibility.Private)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InquiryDiagnosticDescriptors.PropertyMustHavePublicSetter,
                    property.Locations.FirstOrDefault(),
                    entitySymbol.Name,
                    property.Name));
            }
        }

        return columns;
    }

    private static string ResolveColumnName(AttributeData? columnAttribute, AttributeData? foreignKeyAttribute, string propertyName)
    {
        if (columnAttribute is not null)
        {
            return GeneratorHelpers.GetConstructorString(columnAttribute) ?? propertyName;
        }

        // Foreign-key attribute. The 3-arg form (localColumn, referencedTable, referencedColumn)
        // supplies an explicit column name at index 0; the 2-arg form defaults to the property name.
        if (foreignKeyAttribute is { ConstructorArguments.Length: 3 } &&
            foreignKeyAttribute.ConstructorArguments[0].Value is string explicitColumn &&
            !string.IsNullOrWhiteSpace(explicitColumn))
        {
            return explicitColumn;
        }

        return propertyName;
    }

    private static string ReadExpression(GeneratorTypeInfo type, int index)
    {
        var nonNullable = type.NonNullableDisplayName;
        var read = type.SpecialType switch
        {
            SpecialType.System_String => $"reader.GetString({index})",
            SpecialType.System_Boolean => $"reader.GetBoolean({index})",
            SpecialType.System_Int16 => $"reader.GetInt16({index})",
            SpecialType.System_Int32 => $"reader.GetInt32({index})",
            SpecialType.System_Int64 => $"reader.GetInt64({index})",
            SpecialType.System_Single => $"reader.GetFloat({index})",
            SpecialType.System_Double => $"reader.GetDouble({index})",
            SpecialType.System_Decimal => $"reader.GetDecimal({index})",
            SpecialType.System_DateTime => $"reader.GetDateTime({index})",
            _ when type.IsGuid => $"reader.GetGuid({index})",
            _ => $"reader.GetFieldValue<{nonNullable}>({index})",
        };

        if (!type.IsNullable)
        {
            return read;
        }

        if (type.Symbol.IsValueType)
        {
            return $"reader.IsDBNull({index}) ? ({type.DisplayName})null : {read}";
        }

        return $"reader.IsDBNull({index}) ? null : {read}";
    }
}
