using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// Emits the DI registration class consumed by <c>AddInquiry()</c> via reflection.
/// </summary>
internal static class RegistrationEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<EntityRegistrationModel> entityRegistrations,
        ImmutableArray<StoreRegistrationModel> storeRegistrations)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Inquiry.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal sealed class InquiryGeneratedServiceRegistration : global::Inquiry.DependencyInjection.IInquiryServiceRegistration");
        source.AppendLine("    {");
        source.AppendLine("        public void AddServices(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("        {");
        source.AppendLine("            if (services is null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new global::System.ArgumentNullException(nameof(services));");
        source.AppendLine("            }");
        source.AppendLine();

        foreach (var registration in entityRegistrations)
        {
            var entityType = registration.EntityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var materializerType = GeneratorHelpers.GetGeneratedTypeName(registration.EntityType, registration.MaterializerTypeName);
            source.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Inquiry.Materialization.IInquiryEntityMaterializer<{entityType}>, {materializerType}>(services);");
        }

        foreach (var registration in storeRegistrations)
        {
            var storeType = registration.StoreType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var generatedType = GeneratorHelpers.GetGeneratedTypeName(registration.StoreType, registration.GeneratedTypeName);
            // Stores are scoped to align with IInquiry's lifetime: one store instance per
            // request/scope, reused across every call in that scope, but never shared across
            // scopes (so each store sees the scope-local IInquiry). The store itself is
            // stateless after construction (all SQL is in const fields), so scoping is purely
            // about the captured IInquiry reference.
            source.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<{storeType}, {generatedType}>(services);");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("InquiryGeneratedServiceRegistration.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
