using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// Discovers store operation methods and emits the concrete derived store class per user store.
/// </summary>
internal static class StoreProcessor
{
    public static ImmutableArray<StoreMethodModel> Discover(
        SourceProductionContext context,
        INamedTypeSymbol storeSymbol,
        EntityModel entity)
    {
        var methods = ImmutableArray.CreateBuilder<StoreMethodModel>();

        foreach (var method in storeSymbol.GetMembers().OfType<IMethodSymbol>().Where(static m => m.MethodKind == MethodKind.Ordinary))
        {
            var operation = StoreOperationEmitter.GetOperation(method, out var operationAttribute);
            if (operation == StoreOperation.None)
            {
                continue;
            }

            if (!method.IsAbstract)
            {
                context.ReportDiagnostic(Diagnostic.Create(InquiryDiagnosticDescriptors.MethodMustBeAbstract, method.Locations.FirstOrDefault(), method.Name));
                continue;
            }

            var model = StoreOperationEmitter.Validate(context, method, operation, operationAttribute!, entity);
            if (model is not null)
            {
                methods.Add(model);
            }
        }

        return methods.ToImmutable();
    }

    public static StoreRegistrationModel Emit(
        SourceProductionContext context,
        INamedTypeSymbol storeSymbol,
        EntityModel entity,
        ImmutableArray<StoreMethodModel> methods)
    {
        var generatedName = $"Generated{storeSymbol.Name}";
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, storeSymbol);
        source.AppendLine($"{GeneratorHelpers.GetAccessibility(storeSymbol.DeclaredAccessibility)} sealed class {generatedName} : {storeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
        source.AppendLine("{");
        source.AppendLine("    private static readonly global::Inquiry.Sql.InquirySqlColumn[] _columns =");
        source.AppendLine("    {");
        foreach (var column in entity.Columns)
        {
            source.AppendLine($"        new global::Inquiry.Sql.InquirySqlColumn(\"{GeneratorHelpers.Escape(column.PropertyName)}\", \"{GeneratorHelpers.Escape(column.ColumnName)}\", isKey: {GeneratorHelpers.BooleanLiteral(column.IsKey)}, isGenerated: {GeneratorHelpers.BooleanLiteral(column.IsGenerated)}),");
        }
        source.AppendLine("    };");
        source.AppendLine();
        source.AppendLine("    private readonly global::Inquiry.Sql.InquirySqlStatementSet _sqlStatements;");
        source.AppendLine();
        source.AppendLine($"    public {generatedName}(global::Inquiry.IInquiry inquiry, global::Inquiry.Sql.InquirySqlDialect sqlDialect)");
        source.AppendLine("        : base(inquiry)");
        source.AppendLine("    {");
        source.AppendLine($"        _sqlStatements = new global::Inquiry.Sql.InquirySqlStatementBuilder(sqlDialect ?? throw new global::System.ArgumentNullException(nameof(sqlDialect))).Build({GeneratorHelpers.Literal(entity.Schema)}, \"{GeneratorHelpers.Escape(entity.TableName)}\", _columns);");
        source.AppendLine("    }");

        foreach (var method in methods)
        {
            source.AppendLine();
            StoreOperationEmitter.Emit(source, method, entity);
        }

        source.AppendLine("}");
        GeneratorHelpers.AppendNamespaceEnd(source, storeSymbol);

        context.AddSource($"{storeSymbol.Name}.InquiryStore.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new StoreRegistrationModel(storeSymbol, generatedName);
    }
}
