using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Inquiry.Generators.Sql;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// Discovers store operation methods and emits the concrete derived store class per user store.
/// </summary>
/// <remarks>
/// Every SQL string a generated store needs is produced at compile time by a
/// <see cref="SqlBuilder"/> and emitted as a <c>private const string</c> field on the store
/// class. Stores depend only on <see cref="Inquiry.IInquiry"/> at runtime and reuse the same
/// const string for every invocation.
/// </remarks>
internal static class StoreProcessor
{
    public static ImmutableArray<StoreMethodModel> Discover(
        SourceProductionContext context,
        INamedTypeSymbol storeSymbol,
        EntityModel entity)
    {
        var methods = ImmutableArray.CreateBuilder<StoreMethodModel>();

        foreach (var method in storeSymbol.GetMembers().OfType<IMethodSymbol>().Where(static m => m.MethodKind == MethodKind.Ordinary))
        {
            var operation = StoreOperationEmitter.GetOperation(method, out var operationAttribute);
            if (operation == StoreOperation.None)
            {
                continue;
            }

            if (!method.IsPartialDefinition)
            {
                context.ReportDiagnostic(Diagnostic.Create(InquiryDiagnosticDescriptors.MethodMustBePartial, method.Locations.FirstOrDefault(), method.Name));
                continue;
            }

            var model = StoreOperationEmitter.Validate(context, method, operation, operationAttribute!, entity);
            if (model is not null)
            {
                methods.Add(model);
            }
        }

        return methods.ToImmutable();
    }

    public static StoreRegistrationModel Emit(
        SourceProductionContext context,
        INamedTypeSymbol storeSymbol,
        EntityModel entity,
        ImmutableArray<StoreMethodModel> methods,
        Dictionary<string, EntityModel> allEntities,
        SqlBuilder sqlBuilder)
    {
        var keyMayBeDatabaseSupplied = entity.Key.IsGenerated || entity.Key.UseDatabaseDefault;
        var nullableDatabaseSuppliedKeyUpsert = keyMayBeDatabaseSupplied &&
            entity.Key.Type.IsNullable &&
            methods.Any(m => m.Operation == StoreOperation.Upsert);

        // Determine which statements this store actually needs.
        var needsSelectAll = methods.Any(m => m.Operation is StoreOperation.SelectAll or StoreOperation.SelectAllEager);
        var needsSelectByKey = methods.Any(m => m.Operation is StoreOperation.SelectOneByKey or StoreOperation.SelectOneByKeyEager);
        var needsInsert = methods.Any(m => m.Operation == StoreOperation.Insert && !m.ReturnsEntity) ||
            nullableDatabaseSuppliedKeyUpsert && methods.Any(m => m.Operation == StoreOperation.Upsert && !m.ReturnsEntity);
        var needsUpdate = methods.Any(m => m.Operation == StoreOperation.Update && !m.ReturnsEntity);
        var needsUpsert = methods.Any(m => m.Operation == StoreOperation.Upsert && !m.ReturnsEntity);
        var needsInsertReturning = methods.Any(m => m.Operation == StoreOperation.Insert && m.ReturnsEntity) ||
            nullableDatabaseSuppliedKeyUpsert && methods.Any(m => m.Operation == StoreOperation.Upsert && m.ReturnsEntity);
        var needsUpdateReturning = methods.Any(m => m.Operation == StoreOperation.Update && m.ReturnsEntity);
        var needsUpsertReturning = methods.Any(m => m.Operation == StoreOperation.Upsert && m.ReturnsEntity);
        var needsDelete = methods.Any(m => m.Operation == StoreOperation.DeleteOneByKey);

        // Distinct sets of field columns referenced by SelectAllByField methods.
        // Two methods that filter by the same ordered column tuple share one generated SQL field.
        var byFieldOps = methods
            .Where(m => m.Operation == StoreOperation.SelectAllByField && m.FieldColumns.Count > 0)
            .GroupBy(m => BuildFieldSuffix(m.FieldColumns))
            .Select(g => g.First().FieldColumns)
            .ToArray();

        var eagerOps = methods.Where(m => m.Operation is StoreOperation.SelectOneByKeyEager or StoreOperation.SelectAllEager).ToArray();

        var ctx = new SqlBuildContext(sqlBuilder, entity.Schema, entity.TableName, entity.Columns);

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, storeSymbol);
        source.AppendLine($"partial class {storeSymbol.Name}");
        source.AppendLine("{");

        // ---- Per-statement const SQL fields ----
        if (needsSelectAll) AppendConstSql(source, "_sqlSelectAll", sqlBuilder.BuildSelectAllSql(ctx));
        if (needsSelectByKey) AppendConstSql(source, "_sqlSelectByKey", sqlBuilder.BuildSelectByKeySql(ctx));
        if (needsInsert) AppendConstSql(source, "_sqlInsert", sqlBuilder.BuildInsertSql(ctx));
        if (needsUpdate) AppendConstSql(source, "_sqlUpdate", sqlBuilder.BuildUpdateSql(ctx));
        if (needsUpsert) AppendConstSql(source, "_sqlUpsert", sqlBuilder.BuildUpsertSql(ctx));
        if (needsInsertReturning) AppendConstSql(source, "_sqlInsertReturning", sqlBuilder.BuildInsertReturningSql(ctx));
        if (needsUpdateReturning) AppendConstSql(source, "_sqlUpdateReturning", sqlBuilder.BuildUpdateReturningSql(ctx));
        if (needsUpsertReturning) AppendConstSql(source, "_sqlUpsertReturning", sqlBuilder.BuildUpsertReturningSql(ctx));
        if (needsDelete) AppendConstSql(source, "_sqlDeleteByKey", sqlBuilder.BuildDeleteByKeySql(ctx));

        foreach (var fieldColumns in byFieldOps)
        {
            AppendConstSql(source, "_sqlSelectBy_" + BuildFieldSuffix(fieldColumns), sqlBuilder.BuildSelectByFieldSql(ctx, fieldColumns));
        }

        // ---- Child-entity const SQL fields for eager relations ----
        var relationChildEntities = new Dictionary<string, EntityModel>();
        if (eagerOps.Length > 0)
        {
            var emittedRelations = new HashSet<string>();
            foreach (var relation in entity.Relations)
            {
                var childKey = relation.ChildEntitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!emittedRelations.Add(childKey))
                    continue;
                if (!allEntities.TryGetValue(childKey, out var childEntity))
                    continue;

                relationChildEntities[relation.PropertyName] = childEntity;

                var childCtx = new SqlBuildContext(sqlBuilder, childEntity.Schema, childEntity.TableName, childEntity.Columns);

                // One-to-many filters the child table by its FK column; many-to-one filters the
                // parent table by its own key column.
                var filterColumn = relation.IsCollection
                    ? childEntity.Columns.First(c => c.PropertyName == relation.ForeignKeyProperty)
                    : childEntity.Keys[0];

                AppendConstSql(source, "_sql_" + relation.PropertyName, sqlBuilder.BuildSelectByFieldSql(childCtx, new[] { filterColumn }));
                AppendConstSql(source, "_sql_" + relation.PropertyName + "_All", sqlBuilder.BuildSelectAllSql(childCtx));
            }
        }

        // ---- Constructor: forwards to the base. Emitted on the user's class via partial. ----
        source.AppendLine();
        source.AppendLine($"    public {storeSymbol.Name}(global::Inquiry.IInquiry inquiry)");
        source.AppendLine("        : base(inquiry)");
        source.AppendLine("    {");
        source.AppendLine("    }");

        foreach (var method in methods)
        {
            source.AppendLine();
            StoreOperationEmitter.Emit(source, method, entity, relationChildEntities);
        }

        source.AppendLine("}");
        GeneratorHelpers.AppendNamespaceEnd(source, storeSymbol);

        context.AddSource($"{storeSymbol.Name}.InquiryStore.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new StoreRegistrationModel(storeSymbol);
    }

    private static void AppendConstSql(StringBuilder source, string fieldName, string sql)
    {
        source.AppendLine($"    private const string {fieldName} = \"{GeneratorHelpers.Escape(sql)}\";");
    }

    private static string BuildFieldSuffix(IReadOnlyList<ColumnModel> columns)
    {
        if (columns.Count == 1) return columns[0].PropertyName;
        return string.Join("_", columns.Select(c => c.PropertyName));
    }
}
