using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// Discovers store operation methods and emits the concrete derived store class per user store.
/// </summary>
/// <remarks>
/// Every SQL string the store uses is produced by a direct call into the provider's
/// <c>InquirySqlDialect</c> — there is no intermediate builder or statement-set type.
/// Each statement lives on its own readonly field and is initialized once in the constructor.
/// </remarks>
internal static class StoreProcessor
{
    public static ImmutableArray<StoreMethodModel> Discover(
        SourceProductionContext context,
        INamedTypeSymbol storeSymbol,
        EntityModel entity)
    {
        var methods = ImmutableArray.CreateBuilder<StoreMethodModel>();

        foreach (var method in storeSymbol.GetMembers().OfType<IMethodSymbol>().Where(static m => m.MethodKind == MethodKind.Ordinary))
        {
            var operation = StoreOperationEmitter.GetOperation(method, out var operationAttribute);
            if (operation == StoreOperation.None)
            {
                continue;
            }

            if (!method.IsAbstract)
            {
                context.ReportDiagnostic(Diagnostic.Create(InquiryDiagnosticDescriptors.MethodMustBeAbstract, method.Locations.FirstOrDefault(), method.Name));
                continue;
            }

            var model = StoreOperationEmitter.Validate(context, method, operation, operationAttribute!, entity);
            if (model is not null)
            {
                methods.Add(model);
            }
        }

        return methods.ToImmutable();
    }

    public static StoreRegistrationModel Emit(
        SourceProductionContext context,
        INamedTypeSymbol storeSymbol,
        EntityModel entity,
        ImmutableArray<StoreMethodModel> methods,
        Dictionary<string, EntityModel> allEntities)
    {
        var generatedName = $"Generated{storeSymbol.Name}";

        // Determine which statements this store actually needs.
        var needsSelectAll = methods.Any(m => m.Operation is StoreOperation.SelectAll or StoreOperation.SelectAllEager);
        var needsSelectByKey = methods.Any(m => m.Operation is StoreOperation.SelectOneByKey or StoreOperation.SelectOneByKeyEager);
        var needsInsert = methods.Any(m => m.Operation == StoreOperation.Insert && !m.ReturnsEntity);
        var needsUpdate = methods.Any(m => m.Operation == StoreOperation.Update && !m.ReturnsEntity);
        var needsUpsert = methods.Any(m => m.Operation == StoreOperation.Upsert && !m.ReturnsEntity);
        var needsInsertReturning = methods.Any(m => m.Operation == StoreOperation.Insert && m.ReturnsEntity);
        var needsUpdateReturning = methods.Any(m => m.Operation == StoreOperation.Update && m.ReturnsEntity);
        var needsUpsertReturning = methods.Any(m => m.Operation == StoreOperation.Upsert && m.ReturnsEntity);
        var needsDelete = methods.Any(m => m.Operation == StoreOperation.DeleteOneByKey);

        var byFieldOps = methods
            .Where(m => m.Operation == StoreOperation.SelectAllByField && m.FieldColumn is not null)
            .GroupBy(m => m.FieldColumn!.PropertyName)
            .Select(g => g.First().FieldColumn!)
            .ToArray();

        var eagerOps = methods.Where(m => m.Operation is StoreOperation.SelectOneByKeyEager or StoreOperation.SelectAllEager).ToArray();

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, storeSymbol);
        source.AppendLine($"{GeneratorHelpers.GetAccessibility(storeSymbol.DeclaredAccessibility)} sealed class {generatedName} : {storeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}");
        source.AppendLine("{");

        // ---- Column metadata (parent entity) ----
        source.AppendLine("    private static readonly global::Inquiry.Sql.InquirySqlColumn[] _columns =");
        source.AppendLine("    {");
        foreach (var column in entity.Columns)
        {
            source.AppendLine($"        new global::Inquiry.Sql.InquirySqlColumn(\"{GeneratorHelpers.Escape(column.PropertyName)}\", \"{GeneratorHelpers.Escape(column.ColumnName)}\", isKey: {GeneratorHelpers.BooleanLiteral(column.IsKey)}, isGenerated: {GeneratorHelpers.BooleanLiteral(column.IsGenerated)}),");
        }
        source.AppendLine("    };");

        // ---- Column metadata (child entities for eager relations) ----
        var emittedRelations = new HashSet<string>();
        var relationChildEntities = new Dictionary<string, EntityModel>();
        if (eagerOps.Length > 0)
        {
            foreach (var relation in entity.Relations)
            {
                var childKey = relation.ChildEntitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!emittedRelations.Add(childKey))
                    continue;
                if (!allEntities.TryGetValue(childKey, out var childEntity))
                    continue;

                relationChildEntities[relation.PropertyName] = childEntity;

                source.AppendLine($"    private static readonly global::Inquiry.Sql.InquirySqlColumn[] _columns_{relation.PropertyName} =");
                source.AppendLine("    {");
                foreach (var col in childEntity.Columns)
                {
                    source.AppendLine($"        new global::Inquiry.Sql.InquirySqlColumn(\"{GeneratorHelpers.Escape(col.PropertyName)}\", \"{GeneratorHelpers.Escape(col.ColumnName)}\", isKey: {GeneratorHelpers.BooleanLiteral(col.IsKey)}, isGenerated: {GeneratorHelpers.BooleanLiteral(col.IsGenerated)}),");
                }
                source.AppendLine("    };");
            }
        }

        source.AppendLine();

        // ---- Per-statement readonly fields (only what this store uses) ----
        if (needsSelectAll) source.AppendLine("    private readonly string _sqlSelectAll;");
        if (needsSelectByKey) source.AppendLine("    private readonly string _sqlSelectByKey;");
        if (needsInsert) source.AppendLine("    private readonly string _sqlInsert;");
        if (needsUpdate) source.AppendLine("    private readonly string _sqlUpdate;");
        if (needsUpsert) source.AppendLine("    private readonly string _sqlUpsert;");
        if (needsInsertReturning) source.AppendLine("    private readonly string _sqlInsertReturning;");
        if (needsUpdateReturning) source.AppendLine("    private readonly string _sqlUpdateReturning;");
        if (needsUpsertReturning) source.AppendLine("    private readonly string _sqlUpsertReturning;");
        if (needsDelete) source.AppendLine("    private readonly string _sqlDeleteByKey;");

        foreach (var col in byFieldOps)
        {
            source.AppendLine($"    private readonly string _sqlSelectBy_{col.PropertyName};");
        }

        if (eagerOps.Length > 0)
        {
            emittedRelations.Clear();
            foreach (var relation in entity.Relations)
            {
                var childKey = relation.ChildEntitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!emittedRelations.Add(childKey))
                    continue;
                if (!allEntities.ContainsKey(childKey))
                    continue;

                source.AppendLine($"    private readonly string _sql_{relation.PropertyName};");
                source.AppendLine($"    private readonly string _sql_{relation.PropertyName}_All;");
            }
        }

        // ---- Constructor: all SQL built via direct dialect calls ----
        source.AppendLine();
        source.AppendLine($"    public {generatedName}(global::Inquiry.IInquiry inquiry, global::Inquiry.Sql.InquirySqlDialect sqlDialect)");
        source.AppendLine("        : base(inquiry)");
        source.AppendLine("    {");
        source.AppendLine("        if (sqlDialect is null) throw new global::System.ArgumentNullException(nameof(sqlDialect));");
        source.AppendLine($"        var _ctx = sqlDialect.CreateContext({GeneratorHelpers.Literal(entity.Schema)}, \"{GeneratorHelpers.Escape(entity.TableName)}\", _columns);");

        if (needsSelectAll) source.AppendLine("        _sqlSelectAll = sqlDialect.BuildSelectAllSql(_ctx);");
        if (needsSelectByKey) source.AppendLine("        _sqlSelectByKey = sqlDialect.BuildSelectByKeySql(_ctx);");
        if (needsInsert) source.AppendLine("        _sqlInsert = sqlDialect.BuildInsertSql(_ctx);");
        if (needsUpdate) source.AppendLine("        _sqlUpdate = sqlDialect.BuildUpdateSql(_ctx);");
        if (needsUpsert) source.AppendLine("        _sqlUpsert = sqlDialect.BuildUpsertSql(_ctx);");
        if (needsInsertReturning) source.AppendLine("        _sqlInsertReturning = sqlDialect.BuildInsertReturningSql(_ctx);");
        if (needsUpdateReturning) source.AppendLine("        _sqlUpdateReturning = sqlDialect.BuildUpdateReturningSql(_ctx);");
        if (needsUpsertReturning) source.AppendLine("        _sqlUpsertReturning = sqlDialect.BuildUpsertReturningSql(_ctx);");
        if (needsDelete) source.AppendLine("        _sqlDeleteByKey = sqlDialect.BuildDeleteByKeySql(_ctx);");

        foreach (var col in byFieldOps)
        {
            var index = entity.Columns.FindIndex(c => c.PropertyName == col.PropertyName);
            source.AppendLine($"        _sqlSelectBy_{col.PropertyName} = sqlDialect.BuildSelectByFieldSql(_ctx, _columns[{index}]);");
        }

        if (eagerOps.Length > 0)
        {
            emittedRelations.Clear();
            foreach (var relation in entity.Relations)
            {
                var childKey = relation.ChildEntitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (!emittedRelations.Add(childKey))
                    continue;
                if (!allEntities.TryGetValue(childKey, out var childEntity))
                    continue;

                // For one-to-many (collection), filter the related table by its FK column.
                // For many-to-one (single ref), filter the related (parent) table by its own key column.
                var filterIndex = relation.IsCollection
                    ? childEntity.Columns.FindIndex(c => c.PropertyName == relation.ForeignKeyProperty)
                    : childEntity.Columns.FindIndex(c => c.IsKey);

                source.AppendLine($"        var _ctx_{relation.PropertyName} = sqlDialect.CreateContext({GeneratorHelpers.Literal(childEntity.Schema)}, \"{GeneratorHelpers.Escape(childEntity.TableName)}\", _columns_{relation.PropertyName});");
                source.AppendLine($"        _sql_{relation.PropertyName} = sqlDialect.BuildSelectByFieldSql(_ctx_{relation.PropertyName}, _columns_{relation.PropertyName}[{filterIndex}]);");
                source.AppendLine($"        _sql_{relation.PropertyName}_All = sqlDialect.BuildSelectAllSql(_ctx_{relation.PropertyName});");
            }
        }

        source.AppendLine("    }");

        foreach (var method in methods)
        {
            source.AppendLine();
            StoreOperationEmitter.Emit(source, method, entity, relationChildEntities);
        }

        source.AppendLine("}");
        GeneratorHelpers.AppendNamespaceEnd(source, storeSymbol);

        context.AddSource($"{storeSymbol.Name}.InquiryStore.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new StoreRegistrationModel(storeSymbol, generatedName);
    }
}
