using System.Collections.Immutable;
using System.Text;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Inquiry.Generators.Features.ServiceRegistration;

internal static class ServiceRegistrationGenerator
{
    public static void Generate(
        SourceProductionContext context,
        ImmutableArray<EntityRegistrationModel> entityRegistrations,
        ImmutableArray<StoreRegistrationModel> storeRegistrations)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Inquiry.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal sealed class InquiryGeneratedServiceRegistration : global::Inquiry.DependencyInjection.IInquiryServiceRegistration");
        source.AppendLine("    {");
        source.AppendLine("        public void AddServices(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("        {");
        source.AppendLine("            if (services is null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new global::System.ArgumentNullException(nameof(services));");
        source.AppendLine("            }");
        source.AppendLine();

        foreach (var registration in entityRegistrations)
        {
            source.AppendLine(
                $"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Inquiry.Entities.IInquiryEntityMetadata<{registration.EntityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>, {GetGeneratedEntityMetadataTypeName(registration)}>(services);");
            source.AppendLine(
                $"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Inquiry.Materialization.IInquiryEntityMaterializer<{registration.EntityType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>, {GetGeneratedEntityMaterializerTypeName(registration)}>(services);");
        }

        foreach (var registration in storeRegistrations)
        {
            source.AppendLine(
                $"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddTransient<{registration.StoreType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}, {GetGeneratedStoreTypeName(registration)}>(services);");
        }

        source.AppendLine();
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("InquiryGeneratedServiceRegistration.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string GetGeneratedStoreTypeName(StoreRegistrationModel registration)
    {
        return GeneratorHelpers.GetGeneratedTypeName(registration.StoreType, registration.GeneratedTypeName);
    }

    private static string GetGeneratedEntityMaterializerTypeName(EntityRegistrationModel registration)
    {
        return GeneratorHelpers.GetGeneratedTypeName(registration.EntityType, registration.MaterializerTypeName);
    }

    private static string GetGeneratedEntityMetadataTypeName(EntityRegistrationModel registration)
    {
        return GeneratorHelpers.GetGeneratedTypeName(registration.EntityType, registration.MetadataTypeName);
    }
}
