namespace Inquiry.FeatureCatalog;

/// <summary>
/// Per-dialect DDL for the shared feature-catalog tables (<c>VersionedItem</c>, <c>SoftItem</c>,
/// <c>JsonDoc</c>, <c>BulkItem</c>). Mirrors <c>Inquiry.Northwind.NorthwindSchema</c>: one constant per provider, applied by
/// the dialect test harnesses via <c>CreateFromDdlAsync</c>. These tables are deliberately separate from
/// Northwind so the schema-fidelity guardrail (<c>ExpectedNorthwindSchema</c>) stays untouched.
/// </summary>
public static class FeatureSchema
{
    public const string SqliteDdl = """
        CREATE TABLE VersionedItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, Version INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE SoftItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE JsonDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, Owner TEXT NOT NULL, Balance NUMERIC NOT NULL, Tags TEXT NULL);
        CREATE TABLE BulkItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Category TEXT NOT NULL, Amount NUMERIC NOT NULL, Note TEXT NULL);
        """;

    // PostgreSQL folds unquoted identifiers to lowercase, but Inquiry's generated SQL quotes them
    // (case-preserved), so every identifier must be quoted to match — same convention as NorthwindSchema.
    public const string PostgreSqlDdl = """
        CREATE TABLE "VersionedItem" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "Version" INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE "SoftItem" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE "JsonDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Owner" TEXT NOT NULL, "Balance" NUMERIC NOT NULL, "Tags" TEXT NULL);
        CREATE TABLE "BulkItem" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Category" VARCHAR(100) NOT NULL, "Amount" NUMERIC(18,2) NOT NULL, "Note" VARCHAR(200) NULL);
        """;

    public const string SqlServerDdl = """
        CREATE TABLE VersionedItem (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, [Version] INT NOT NULL DEFAULT 0);
        CREATE TABLE SoftItem (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0);
        CREATE TABLE JsonDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Owner NVARCHAR(200) NOT NULL, Balance DECIMAL(18,2) NOT NULL, Tags NVARCHAR(MAX) NULL);
        CREATE TABLE BulkItem (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Category NVARCHAR(100) NOT NULL, Amount DECIMAL(18,2) NOT NULL, Note NVARCHAR(200) NULL);
        """;

    public const string MySqlDdl = """
        CREATE TABLE VersionedItem (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, Version INT NOT NULL DEFAULT 0);
        CREATE TABLE SoftItem (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(200) NOT NULL, IsDeleted TINYINT(1) NOT NULL DEFAULT 0);
        CREATE TABLE JsonDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Owner VARCHAR(200) NOT NULL, Balance DECIMAL(18,2) NOT NULL, Tags VARCHAR(2000) NULL);
        CREATE TABLE BulkItem (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Category VARCHAR(100) NOT NULL, Amount DECIMAL(18,2) NOT NULL, Note VARCHAR(200) NULL);
        """;

    // Oracle: identity columns (12c+), NUMBER(1) for bool. Identifiers are left UNQUOTED so Oracle folds
    // them to uppercase, matching Inquiry's unquoted Oracle SQL generation (Version is not reserved).
    // Statements are split on ';' by the Oracle harness because Oracle rejects batched DDL in one command.
    public const string OracleDdl = """
        CREATE TABLE VersionedItem (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, Version NUMBER(10) DEFAULT 0 NOT NULL);
        CREATE TABLE SoftItem (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL);
        CREATE TABLE JsonDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Owner VARCHAR2(200) NOT NULL, Balance NUMBER(18,2) NOT NULL, Tags VARCHAR2(2000) NULL);
        CREATE TABLE BulkItem (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Category VARCHAR2(100) NOT NULL, Amount NUMBER(18,2) NOT NULL, Note VARCHAR2(200) NULL);
        """;

    // ---------------------------------------------------------------------------
    // Repro schema for bugs #48 (read) and #49 (write): unsigned / sbyte types.
    //
    // Column types chosen to match what the generator's MapColumnType emits:
    //   sbyte   → DbTypeClass.Byte  → TINYINT  (SQL Server) / INTEGER (SQLite)
    //   ushort  → DbTypeClass.Int16 → SMALLINT (SQL Server) / INTEGER (SQLite)
    //   uint    → DbTypeClass.Int32 → INT      (SQL Server) / INTEGER (SQLite)
    //   ulong   → DbTypeClass.Int64 → BIGINT   (SQL Server) / INTEGER (SQLite)
    //   Enums use the same class as their underlying type.
    //
    // The binder stores the REINTERPRETED same-width signed value, which always fits the signed
    // column: sbyte -1 → byte 255 (TINYINT 0-255), ushort 40000 → short -25536 (SMALLINT),
    // uint 3_000_000_000 → int -1_294_967_296 (INT), ulong.MaxValue → long -1 (BIGINT). The
    // materializer reverses the cast on read, so the full unsigned/sbyte range round-trips.
    // ---------------------------------------------------------------------------

    /// <summary>SQL Server DDL for the <see cref="UnsignedTypesItem"/> repro table.</summary>
    public const string UnsignedTypesSqlServerDdl = """
        CREATE TABLE UnsignedTypesItem (
            Id          INT          NOT NULL PRIMARY KEY,
            ByteVal     TINYINT      NOT NULL,
            Int16Val    SMALLINT     NOT NULL,
            Int32Val    INT          NOT NULL,
            Int64Val    BIGINT       NOT NULL,
            SByteVal    TINYINT      NOT NULL,
            UInt16Val   SMALLINT     NOT NULL,
            UInt32Val   INT          NOT NULL,
            UInt64Val   BIGINT       NOT NULL,
            EnumInt32Val  INT        NOT NULL,
            EnumSByteVal  TINYINT    NOT NULL,
            EnumUInt16Val SMALLINT   NOT NULL,
            EnumUInt32Val INT        NOT NULL,
            EnumUInt64Val BIGINT     NOT NULL
        );
        """;

    /// <summary>SQLite DDL for the <see cref="UnsignedTypesItem"/> repro table.</summary>
    public const string UnsignedTypesSqliteDdl = """
        CREATE TABLE UnsignedTypesItem (
            Id            INTEGER NOT NULL PRIMARY KEY,
            ByteVal       INTEGER NOT NULL,
            Int16Val      INTEGER NOT NULL,
            Int32Val      INTEGER NOT NULL,
            Int64Val      INTEGER NOT NULL,
            SByteVal      INTEGER NOT NULL,
            UInt16Val     INTEGER NOT NULL,
            UInt32Val     INTEGER NOT NULL,
            UInt64Val     INTEGER NOT NULL,
            EnumInt32Val  INTEGER NOT NULL,
            EnumSByteVal  INTEGER NOT NULL,
            EnumUInt16Val INTEGER NOT NULL,
            EnumUInt32Val INTEGER NOT NULL,
            EnumUInt64Val INTEGER NOT NULL
        );
        """;

    /// <summary>PostgreSQL DDL for the <see cref="UnsignedTypesItem"/> repro table.</summary>
    public const string UnsignedTypesPostgreSqlDdl = """
        CREATE TABLE "UnsignedTypesItem" (
            "Id"            INTEGER NOT NULL PRIMARY KEY,
            "ByteVal"       SMALLINT NOT NULL,
            "Int16Val"      SMALLINT NOT NULL,
            "Int32Val"      INTEGER NOT NULL,
            "Int64Val"      BIGINT NOT NULL,
            "SByteVal"      SMALLINT NOT NULL,
            "UInt16Val"     SMALLINT NOT NULL,
            "UInt32Val"     INTEGER NOT NULL,
            "UInt64Val"     BIGINT NOT NULL,
            "EnumInt32Val"  INTEGER NOT NULL,
            "EnumSByteVal"  SMALLINT NOT NULL,
            "EnumUInt16Val" SMALLINT NOT NULL,
            "EnumUInt32Val" INTEGER NOT NULL,
            "EnumUInt64Val" BIGINT NOT NULL
        );
        """;

    /// <summary>MySQL / MariaDB DDL for the <see cref="UnsignedTypesItem"/> repro table.</summary>
    public const string UnsignedTypesMySqlDdl = """
        CREATE TABLE UnsignedTypesItem (
            Id            INT NOT NULL PRIMARY KEY,
            ByteVal       SMALLINT NOT NULL,
            Int16Val      SMALLINT NOT NULL,
            Int32Val      INT NOT NULL,
            Int64Val      BIGINT NOT NULL,
            SByteVal      SMALLINT NOT NULL,
            UInt16Val     SMALLINT NOT NULL,
            UInt32Val     INT NOT NULL,
            UInt64Val     BIGINT NOT NULL,
            EnumInt32Val  INT NOT NULL,
            EnumSByteVal  SMALLINT NOT NULL,
            EnumUInt16Val SMALLINT NOT NULL,
            EnumUInt32Val INT NOT NULL,
            EnumUInt64Val BIGINT NOT NULL
        );
        """;

    /// <summary>Oracle DDL for the <see cref="UnsignedTypesItem"/> repro table.</summary>
    public const string UnsignedTypesOracleDdl = """
        CREATE TABLE UnsignedTypesItem (
            Id            NUMBER(10) NOT NULL PRIMARY KEY,
            ByteVal       NUMBER(3) NOT NULL,
            Int16Val      NUMBER(5) NOT NULL,
            Int32Val      NUMBER(10) NOT NULL,
            Int64Val      NUMBER(19) NOT NULL,
            SByteVal      NUMBER(3) NOT NULL,
            UInt16Val     NUMBER(5) NOT NULL,
            UInt32Val     NUMBER(10) NOT NULL,
            UInt64Val     NUMBER(19) NOT NULL,
            EnumInt32Val  NUMBER(10) NOT NULL,
            EnumSByteVal  NUMBER(3) NOT NULL,
            EnumUInt16Val NUMBER(5) NOT NULL,
            EnumUInt32Val NUMBER(10) NOT NULL,
            EnumUInt64Val NUMBER(19) NOT NULL
        )
        """;

    // ---------------------------------------------------------------------------
    // Repro schema for the eager-load sibling of #49: a uint KEY above int.MaxValue.
    // uint → INT (SQL Server) / INTEGER (SQLite); the eager-load binder passes the raw
    // boxed uint with DbType.Int32, which the runtime binder reinterprets to a signed int.
    // ---------------------------------------------------------------------------

    /// <summary>SQL Server DDL for the <see cref="UnsignedKeyParent"/> / <see cref="UnsignedKeyChild"/> repro tables.</summary>
    public const string UnsignedKeyEagerSqlServerDdl = """
        CREATE TABLE UnsignedKeyParent (
            Id   INT          NOT NULL PRIMARY KEY,
            Name NVARCHAR(100) NOT NULL
        );
        CREATE TABLE UnsignedKeyChild (
            Id       INT          NOT NULL PRIMARY KEY,
            ParentId INT          NOT NULL,
            Label    NVARCHAR(100) NOT NULL
        );
        """;

    /// <summary>SQLite DDL for the <see cref="UnsignedKeyParent"/> / <see cref="UnsignedKeyChild"/> repro tables.</summary>
    public const string UnsignedKeyEagerSqliteDdl = """
        CREATE TABLE UnsignedKeyParent (
            Id   INTEGER NOT NULL PRIMARY KEY,
            Name TEXT    NOT NULL
        );
        CREATE TABLE UnsignedKeyChild (
            Id       INTEGER NOT NULL PRIMARY KEY,
            ParentId INTEGER NOT NULL,
            Label    TEXT    NOT NULL
        );
        """;

    /// <summary>PostgreSQL DDL for the <see cref="UnsignedKeyParent"/> / <see cref="UnsignedKeyChild"/> repro tables.</summary>
    public const string UnsignedKeyEagerPostgreSqlDdl = """
        CREATE TABLE "UnsignedKeyParent" (
            "Id"   INTEGER NOT NULL PRIMARY KEY,
            "Name" TEXT NOT NULL
        );
        CREATE TABLE "UnsignedKeyChild" (
            "Id"       INTEGER NOT NULL PRIMARY KEY,
            "ParentId" INTEGER NOT NULL,
            "Label"    TEXT NOT NULL
        );
        """;

    /// <summary>MySQL / MariaDB DDL for the <see cref="UnsignedKeyParent"/> / <see cref="UnsignedKeyChild"/> repro tables.</summary>
    public const string UnsignedKeyEagerMySqlDdl = """
        CREATE TABLE UnsignedKeyParent (
            Id   INT NOT NULL PRIMARY KEY,
            Name VARCHAR(100) NOT NULL
        );
        CREATE TABLE UnsignedKeyChild (
            Id       INT NOT NULL PRIMARY KEY,
            ParentId INT NOT NULL,
            Label    VARCHAR(100) NOT NULL
        );
        """;

    /// <summary>Oracle DDL for the <see cref="UnsignedKeyParent"/> / <see cref="UnsignedKeyChild"/> repro tables.</summary>
    public const string UnsignedKeyEagerOracleDdl = """
        CREATE TABLE UnsignedKeyParent (
            Id   NUMBER(10) NOT NULL PRIMARY KEY,
            Name VARCHAR2(100) NOT NULL
        );
        CREATE TABLE UnsignedKeyChild (
            Id       NUMBER(10) NOT NULL PRIMARY KEY,
            ParentId NUMBER(10) NOT NULL,
            Label    VARCHAR2(100) NOT NULL
        )
        """;

    // ---------------------------------------------------------------------------
    // #70 mixed-relation eager tables: EagerMixedPost (parent) carries both a to-one
    // reference to EagerMixedAuthor and a to-many collection of EagerMixedTag, so one
    // eager load batches three SELECTs into a single command. Client-supplied int keys
    // (no IDENTITY/SEQUENCE) and no FK constraints, matching the UnsignedKeyEager tables.
    // ---------------------------------------------------------------------------

    /// <summary>SQL Server DDL for the <see cref="EagerMixedPost"/> mixed-relation eager tables.</summary>
    public const string EagerMixedSqlServerDdl = """
        CREATE TABLE EagerMixedAuthor (
            Id   INT           NOT NULL PRIMARY KEY,
            Name NVARCHAR(100) NOT NULL
        );
        CREATE TABLE EagerMixedPost (
            Id       INT           NOT NULL PRIMARY KEY,
            AuthorId INT           NOT NULL,
            Title    NVARCHAR(200) NOT NULL
        );
        CREATE TABLE EagerMixedTag (
            Id     INT           NOT NULL PRIMARY KEY,
            PostId INT           NOT NULL,
            Label  NVARCHAR(100) NOT NULL
        );
        """;

    /// <summary>SQLite DDL for the <see cref="EagerMixedPost"/> mixed-relation eager tables.</summary>
    public const string EagerMixedSqliteDdl = """
        CREATE TABLE EagerMixedAuthor (
            Id   INTEGER NOT NULL PRIMARY KEY,
            Name TEXT    NOT NULL
        );
        CREATE TABLE EagerMixedPost (
            Id       INTEGER NOT NULL PRIMARY KEY,
            AuthorId INTEGER NOT NULL,
            Title    TEXT    NOT NULL
        );
        CREATE TABLE EagerMixedTag (
            Id     INTEGER NOT NULL PRIMARY KEY,
            PostId INTEGER NOT NULL,
            Label  TEXT    NOT NULL
        );
        """;

    /// <summary>PostgreSQL DDL for the <see cref="EagerMixedPost"/> mixed-relation eager tables.</summary>
    public const string EagerMixedPostgreSqlDdl = """
        CREATE TABLE "EagerMixedAuthor" (
            "Id"   INTEGER NOT NULL PRIMARY KEY,
            "Name" TEXT NOT NULL
        );
        CREATE TABLE "EagerMixedPost" (
            "Id"       INTEGER NOT NULL PRIMARY KEY,
            "AuthorId" INTEGER NOT NULL,
            "Title"    TEXT NOT NULL
        );
        CREATE TABLE "EagerMixedTag" (
            "Id"     INTEGER NOT NULL PRIMARY KEY,
            "PostId" INTEGER NOT NULL,
            "Label"  TEXT NOT NULL
        );
        """;

    /// <summary>MySQL / MariaDB DDL for the <see cref="EagerMixedPost"/> mixed-relation eager tables.</summary>
    public const string EagerMixedMySqlDdl = """
        CREATE TABLE EagerMixedAuthor (
            Id   INT NOT NULL PRIMARY KEY,
            Name VARCHAR(100) NOT NULL
        );
        CREATE TABLE EagerMixedPost (
            Id       INT NOT NULL PRIMARY KEY,
            AuthorId INT NOT NULL,
            Title    VARCHAR(200) NOT NULL
        );
        CREATE TABLE EagerMixedTag (
            Id     INT NOT NULL PRIMARY KEY,
            PostId INT NOT NULL,
            Label  VARCHAR(100) NOT NULL
        );
        """;

    /// <summary>Oracle DDL for the <see cref="EagerMixedPost"/> mixed-relation eager tables.</summary>
    public const string EagerMixedOracleDdl = """
        CREATE TABLE EagerMixedAuthor (
            Id   NUMBER(10) NOT NULL PRIMARY KEY,
            Name VARCHAR2(100) NOT NULL
        );
        CREATE TABLE EagerMixedPost (
            Id       NUMBER(10) NOT NULL PRIMARY KEY,
            AuthorId NUMBER(10) NOT NULL,
            Title    VARCHAR2(200) NOT NULL
        );
        CREATE TABLE EagerMixedTag (
            Id     NUMBER(10) NOT NULL PRIMARY KEY,
            PostId NUMBER(10) NOT NULL,
            Label  VARCHAR2(100) NOT NULL
        )
        """;

    // ---------------------------------------------------------------------------
    // GlobalFilter integration tables: GlobalFilterDoc (publish gate + soft delete)
    // and GlobalFilterTicket (KeepWhen = false archive gate).
    // ---------------------------------------------------------------------------

    // Runtime-parameterized filter (#82 phase B): TenantScopedDoc's reads bind @__gf_TenantId from
    // the ambient InquiryFilterContext.
    public const string TenantScopedDocSqliteDdl =
        "CREATE TABLE TenantScopedDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, TenantId INTEGER NOT NULL, Title TEXT NOT NULL, IsActive INTEGER NOT NULL DEFAULT 1);";

    // Write-enforced filter (#82 phase C): WriteEnforcedDoc composes @__gf_TenantId onto key-based
    // writes as well as reads.
    public const string WriteEnforcedDocSqliteDdl =
        "CREATE TABLE WriteEnforcedDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, TenantId INTEGER NOT NULL, Title TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0);";

    public const string WriteEnforcedDocPostgreSqlDdl =
        """CREATE TABLE "WriteEnforcedDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "TenantId" BIGINT NOT NULL, "Title" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE);""";

    public const string WriteEnforcedDocSqlServerDdl =
        "CREATE TABLE WriteEnforcedDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, TenantId BIGINT NOT NULL, Title NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0);";

    public const string WriteEnforcedDocMySqlDdl =
        "CREATE TABLE WriteEnforcedDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, TenantId BIGINT NOT NULL, Title VARCHAR(200) NOT NULL, IsDeleted TINYINT(1) NOT NULL DEFAULT 0);";

    public const string WriteEnforcedDocOracleDdl =
        "CREATE TABLE WriteEnforcedDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, TenantId NUMBER(19) NOT NULL, Title VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL)";

    public const string GlobalFilterSqliteDdl = """
        CREATE TABLE GlobalFilterDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, IsPublished INTEGER NOT NULL DEFAULT 0, IsDeleted INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE GlobalFilterTicket (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, IsArchived INTEGER NOT NULL DEFAULT 0);
        """;

    public const string GlobalFilterPostgreSqlDdl = """
        CREATE TABLE "GlobalFilterDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" TEXT NOT NULL, "IsPublished" BOOLEAN NOT NULL DEFAULT FALSE, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE "GlobalFilterTicket" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "IsArchived" BOOLEAN NOT NULL DEFAULT FALSE);
        """;

    public const string GlobalFilterSqlServerDdl = """
        CREATE TABLE GlobalFilterDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, IsPublished BIT NOT NULL DEFAULT 0, IsDeleted BIT NOT NULL DEFAULT 0);
        CREATE TABLE GlobalFilterTicket (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, IsArchived BIT NOT NULL DEFAULT 0);
        """;

    public const string GlobalFilterMySqlDdl = """
        CREATE TABLE GlobalFilterDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(200) NOT NULL, IsPublished TINYINT(1) NOT NULL DEFAULT 0, IsDeleted TINYINT(1) NOT NULL DEFAULT 0);
        CREATE TABLE GlobalFilterTicket (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, IsArchived TINYINT(1) NOT NULL DEFAULT 0);
        """;

    public const string GlobalFilterOracleDdl = """
        CREATE TABLE GlobalFilterDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR2(200) NOT NULL, IsPublished NUMBER(1) DEFAULT 0 NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL);
        CREATE TABLE GlobalFilterTicket (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, IsArchived NUMBER(1) DEFAULT 0 NOT NULL);
        """;

    // ---------------------------------------------------------------------------
    // ManyToMany integration tables: M2MOrder, M2MProduct, M2MOrderProduct (junction).
    // ---------------------------------------------------------------------------

    public const string ManyToManySqliteDdl =
        "CREATE TABLE M2MOrder (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0, IsActive INTEGER NOT NULL DEFAULT 1);" +
        "CREATE TABLE M2MProduct (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0, IsActive INTEGER NOT NULL DEFAULT 1);" +
        "CREATE TABLE M2MOrderProduct (OrderId INTEGER NOT NULL, ProductId INTEGER NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0, IsActive INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (OrderId, ProductId));";

    public const string ManyToManyPostgreSqlDdl = """
        CREATE TABLE "M2MOrder" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE, "IsActive" BOOLEAN NOT NULL DEFAULT TRUE);
        CREATE TABLE "M2MProduct" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE, "IsActive" BOOLEAN NOT NULL DEFAULT TRUE);
        CREATE TABLE "M2MOrderProduct" ("OrderId" BIGINT NOT NULL, "ProductId" BIGINT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE, "IsActive" BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY ("OrderId", "ProductId"));
        """;

    public const string ManyToManySqlServerDdl = """
        CREATE TABLE M2MOrder (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1);
        CREATE TABLE M2MProduct (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1);
        CREATE TABLE M2MOrderProduct (OrderId BIGINT NOT NULL, ProductId BIGINT NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1, PRIMARY KEY (OrderId, ProductId));
        """;

    public const string ManyToManyMySqlDdl = """
        CREATE TABLE M2MOrder (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(200) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE, IsActive BOOLEAN NOT NULL DEFAULT TRUE);
        CREATE TABLE M2MProduct (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE, IsActive BOOLEAN NOT NULL DEFAULT TRUE);
        CREATE TABLE M2MOrderProduct (OrderId BIGINT NOT NULL, ProductId BIGINT NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE, IsActive BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (OrderId, ProductId));
        """;

    public const string ManyToManyOracleDdl = """
        CREATE TABLE M2MOrder (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL, IsActive NUMBER(1) DEFAULT 1 NOT NULL);
        CREATE TABLE M2MProduct (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL, IsActive NUMBER(1) DEFAULT 1 NOT NULL);
        CREATE TABLE M2MOrderProduct (OrderId NUMBER NOT NULL, ProductId NUMBER NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL, IsActive NUMBER(1) DEFAULT 1 NOT NULL, PRIMARY KEY (OrderId, ProductId));
        """;

    // ---------------------------------------------------------------------------
    // Composite-key many-to-many: M2MPost, M2MTag keyed (TenantId, Slug), M2MPostTag (junction).
    // The seeded tags deliberately reuse each key component across rows — tenant 1 has "red" and
    // "blue", and "red" exists under tenants 1 and 2 — so a join matching on one component alone
    // returns rows the association does not link.
    // ---------------------------------------------------------------------------

    public const string CompositeManyToManySqliteDdl =
        "CREATE TABLE M2MPost (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0);" +
        "CREATE TABLE M2MTag (TenantId INTEGER NOT NULL, Slug TEXT NOT NULL, Label TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0, IsActive INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (TenantId, Slug));" +
        "CREATE TABLE M2MPostTag (PostId INTEGER NOT NULL, TenantId INTEGER NOT NULL, Slug TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (PostId, TenantId, Slug));";

    public const string CompositeManyToManyPostgreSqlDdl = """
        CREATE TABLE "M2MPost" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE "M2MTag" ("TenantId" INTEGER NOT NULL, "Slug" VARCHAR(64) NOT NULL, "Label" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE, "IsActive" BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY ("TenantId", "Slug"));
        CREATE TABLE "M2MPostTag" ("PostId" BIGINT NOT NULL, "TenantId" INTEGER NOT NULL, "Slug" VARCHAR(64) NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY ("PostId", "TenantId", "Slug"));
        """;

    public const string CompositeManyToManySqlServerDdl = """
        CREATE TABLE M2MPost (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0);
        CREATE TABLE M2MTag (TenantId INT NOT NULL, Slug NVARCHAR(64) NOT NULL, Label NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1, PRIMARY KEY (TenantId, Slug));
        CREATE TABLE M2MPostTag (PostId BIGINT NOT NULL, TenantId INT NOT NULL, Slug NVARCHAR(64) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0, PRIMARY KEY (PostId, TenantId, Slug));
        """;

    public const string CompositeManyToManyMySqlDdl = """
        CREATE TABLE M2MPost (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE M2MTag (TenantId INT NOT NULL, Slug VARCHAR(64) NOT NULL, Label VARCHAR(200) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE, IsActive BOOLEAN NOT NULL DEFAULT TRUE, PRIMARY KEY (TenantId, Slug));
        CREATE TABLE M2MPostTag (PostId BIGINT NOT NULL, TenantId INT NOT NULL, Slug VARCHAR(64) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY (PostId, TenantId, Slug));
        """;

    public const string CompositeManyToManyOracleDdl = """
        CREATE TABLE M2MPost (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL);
        CREATE TABLE M2MTag (TenantId NUMBER(10) NOT NULL, Slug VARCHAR2(64) NOT NULL, Label VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL, IsActive NUMBER(1) DEFAULT 1 NOT NULL, PRIMARY KEY (TenantId, Slug));
        CREATE TABLE M2MPostTag (PostId NUMBER NOT NULL, TenantId NUMBER(10) NOT NULL, Slug VARCHAR2(64) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL, PRIMARY KEY (PostId, TenantId, Slug));
        """;

    // ---------------------------------------------------------------------------
    // Auto-managed junction: M2MAuthor, M2MBook, and the SYNTHESIZED M2MAuthor_M2MBook.
    //
    // The junction's table and column names are not chosen here — they are what the generator derives
    // from the two table names sorted ordinally, so this DDL must mirror it exactly. The integration
    // tests assert the generated SQL references these names, which is what catches drift.
    //
    // Authors, books, and links are all seeded from DDL: keys are client-supplied and an auto-managed
    // junction is read-only, so no store can insert a link row. Author 3 and book 30 are soft-deleted,
    // and book 40 is globally filtered, to prove the eager read still applies each side's own
    // active-row filter — the synthesized junction has no filter columns that could do it instead.
    // ---------------------------------------------------------------------------

    public const string AutoJunctionSqliteDdl =
        "CREATE TABLE M2MAuthor (Id INTEGER NOT NULL PRIMARY KEY, Name TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0);" +
        "CREATE TABLE M2MBook (Id INTEGER NOT NULL PRIMARY KEY, Title TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0, IsActive INTEGER NOT NULL DEFAULT 1);" +
        "CREATE TABLE M2MAuthor_M2MBook (M2MAuthor_Id INTEGER NOT NULL, M2MBook_Id INTEGER NOT NULL, PRIMARY KEY (M2MAuthor_Id, M2MBook_Id));" +
        AutoJunctionSeed;

    public const string AutoJunctionPostgreSqlDdl = """
        CREATE TABLE "M2MAuthor" ("Id" BIGINT NOT NULL PRIMARY KEY, "Name" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE "M2MBook" ("Id" BIGINT NOT NULL PRIMARY KEY, "Title" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE, "IsActive" BOOLEAN NOT NULL DEFAULT TRUE);
        CREATE TABLE "M2MAuthor_M2MBook" ("M2MAuthor_Id" BIGINT NOT NULL, "M2MBook_Id" BIGINT NOT NULL, PRIMARY KEY ("M2MAuthor_Id", "M2MBook_Id"));
        INSERT INTO "M2MAuthor" ("Id", "Name", "IsDeleted") VALUES (1, 'Ada', FALSE), (2, 'Grace', FALSE), (3, 'Deleted', TRUE), (4, 'Unlinked', FALSE);
        INSERT INTO "M2MBook" ("Id", "Title", "IsDeleted", "IsActive") VALUES (10, 'Analytical', FALSE, TRUE), (20, 'Compilers', FALSE, TRUE), (30, 'Retired', TRUE, TRUE), (40, 'Muted', FALSE, FALSE);
        INSERT INTO "M2MAuthor_M2MBook" ("M2MAuthor_Id", "M2MBook_Id") VALUES (1, 10), (1, 20), (2, 20), (1, 30), (3, 10), (1, 40);
        """;

    public const string AutoJunctionSqlServerDdl = """
        CREATE TABLE M2MAuthor (Id BIGINT NOT NULL PRIMARY KEY, Name NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0);
        CREATE TABLE M2MBook (Id BIGINT NOT NULL PRIMARY KEY, Title NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0, IsActive BIT NOT NULL DEFAULT 1);
        CREATE TABLE M2MAuthor_M2MBook (M2MAuthor_Id BIGINT NOT NULL, M2MBook_Id BIGINT NOT NULL, PRIMARY KEY (M2MAuthor_Id, M2MBook_Id));
        INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (1, 'Ada', 0), (2, 'Grace', 0), (3, 'Deleted', 1), (4, 'Unlinked', 0);
        INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (10, 'Analytical', 0, 1), (20, 'Compilers', 0, 1), (30, 'Retired', 1, 1), (40, 'Muted', 0, 0);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 10), (1, 20), (2, 20), (1, 30), (3, 10), (1, 40);
        """;

    public const string AutoJunctionMySqlDdl = """
        CREATE TABLE M2MAuthor (Id BIGINT NOT NULL PRIMARY KEY, Name VARCHAR(200) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE M2MBook (Id BIGINT NOT NULL PRIMARY KEY, Title VARCHAR(200) NOT NULL, IsDeleted BOOLEAN NOT NULL DEFAULT FALSE, IsActive BOOLEAN NOT NULL DEFAULT TRUE);
        CREATE TABLE M2MAuthor_M2MBook (M2MAuthor_Id BIGINT NOT NULL, M2MBook_Id BIGINT NOT NULL, PRIMARY KEY (M2MAuthor_Id, M2MBook_Id));
        INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (1, 'Ada', FALSE), (2, 'Grace', FALSE), (3, 'Deleted', TRUE), (4, 'Unlinked', FALSE);
        INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (10, 'Analytical', FALSE, TRUE), (20, 'Compilers', FALSE, TRUE), (30, 'Retired', TRUE, TRUE), (40, 'Muted', FALSE, FALSE);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 10), (1, 20), (2, 20), (1, 30), (3, 10), (1, 40);
        """;

    // Oracle has no multi-row VALUES and rejects a trailing semicolon on the last statement of a
    // script the harness splits, so every insert is its own statement.
    public const string AutoJunctionOracleDdl = """
        CREATE TABLE M2MAuthor (Id NUMBER NOT NULL PRIMARY KEY, Name VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL);
        CREATE TABLE M2MBook (Id NUMBER NOT NULL PRIMARY KEY, Title VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL, IsActive NUMBER(1) DEFAULT 1 NOT NULL);
        CREATE TABLE M2MAuthor_M2MBook (M2MAuthor_Id NUMBER NOT NULL, M2MBook_Id NUMBER NOT NULL, PRIMARY KEY (M2MAuthor_Id, M2MBook_Id));
        INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (1, 'Ada', 0);
        INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (2, 'Grace', 0);
        INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (3, 'Deleted', 1);
        INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (4, 'Unlinked', 0);
        INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (10, 'Analytical', 0, 1);
        INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (20, 'Compilers', 0, 1);
        INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (30, 'Retired', 1, 1);
        INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (40, 'Muted', 0, 0);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 10);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 20);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (2, 20);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 30);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (3, 10);
        INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 40);
        """;

    /// <summary>
    /// Author 1 → books 10, 20 (plus soft-deleted 30 and globally filtered 40); author 2 → book 20;
    /// soft-deleted author 3 → book 10.
    /// </summary>
    private const string AutoJunctionSeed =
        "INSERT INTO M2MAuthor (Id, Name, IsDeleted) VALUES (1, 'Ada', 0), (2, 'Grace', 0), (3, 'Deleted', 1), (4, 'Unlinked', 0);" +
        "INSERT INTO M2MBook (Id, Title, IsDeleted, IsActive) VALUES (10, 'Analytical', 0, 1), (20, 'Compilers', 0, 1), (30, 'Retired', 1, 1), (40, 'Muted', 0, 0);" +
        "INSERT INTO M2MAuthor_M2MBook (M2MAuthor_Id, M2MBook_Id) VALUES (1, 10), (1, 20), (2, 20), (1, 30), (3, 10), (1, 40);";

    // ---------------------------------------------------------------------------
    // AuditTimestamp integration table: AuditDoc (CreatedAt + ModifiedAt).
    // ---------------------------------------------------------------------------

    public const string AuditTimestampSqliteDdl =
        "CREATE TABLE AuditDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, CreatedAt TEXT NOT NULL, ModifiedAt TEXT NOT NULL);";

    public const string AuditTimestampPostgreSqlDdl = """
        CREATE TABLE "AuditDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "CreatedAt" TIMESTAMP NOT NULL, "ModifiedAt" TIMESTAMP NOT NULL);
        """;

    public const string AuditTimestampSqlServerDdl = """
        CREATE TABLE AuditDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, CreatedAt DATETIME2 NOT NULL, ModifiedAt DATETIME2 NOT NULL);
        """;

    public const string AuditTimestampMySqlDdl = """
        CREATE TABLE AuditDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, CreatedAt DATETIME(6) NOT NULL, ModifiedAt DATETIME(6) NOT NULL);
        """;

    public const string AuditTimestampOracleDdl = """
        CREATE TABLE AuditDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, CreatedAt TIMESTAMP NOT NULL, ModifiedAt TIMESTAMP NOT NULL);
        """;

    // ---------------------------------------------------------------------------
    // AuditUser integration table: AuditUserDoc (CreatedBy + ModifiedBy).
    // ---------------------------------------------------------------------------

    public const string AuditUserSqliteDdl =
        "CREATE TABLE AuditUserDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, CreatedBy TEXT NULL, ModifiedBy TEXT NULL);";

    public const string AuditUserPostgreSqlDdl = """
        CREATE TABLE "AuditUserDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "CreatedBy" TEXT NULL, "ModifiedBy" TEXT NULL);
        """;

    public const string AuditUserSqlServerDdl = """
        CREATE TABLE AuditUserDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, CreatedBy NVARCHAR(200) NULL, ModifiedBy NVARCHAR(200) NULL);
        """;

    public const string AuditUserMySqlDdl = """
        CREATE TABLE AuditUserDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, CreatedBy VARCHAR(200) NULL, ModifiedBy VARCHAR(200) NULL);
        """;

    public const string AuditUserOracleDdl = """
        CREATE TABLE AuditUserDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, CreatedBy VARCHAR2(200) NULL, ModifiedBy VARCHAR2(200) NULL);
        """;

    // ---------------------------------------------------------------------------
    // ComputedColumn integration table: ComputedPerson (FullName computed from
    // FirstName + LastName). Expression syntax varies by dialect.
    // ---------------------------------------------------------------------------

    public const string ComputedColumnSqliteDdl =
        "CREATE TABLE ComputedPerson (Id INTEGER PRIMARY KEY AUTOINCREMENT, FirstName TEXT NOT NULL, LastName TEXT NOT NULL, FullName AS (FirstName || ' ' || LastName), \"Base Value\" INTEGER NOT NULL, \"MixedCaseValue\" INTEGER NOT NULL, \"Computed Total\" AS (\"Base Value\" + \"MixedCaseValue\"));";

    public const string ComputedColumnPostgreSqlDdl = """
        CREATE TABLE "ComputedPerson" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "FirstName" TEXT NOT NULL, "LastName" TEXT NOT NULL, "FullName" TEXT GENERATED ALWAYS AS ("FirstName" || ' ' || "LastName") STORED, "Base Value" INTEGER NOT NULL, "MixedCaseValue" INTEGER NOT NULL, "Computed Total" INTEGER GENERATED ALWAYS AS ("Base Value" + "MixedCaseValue") STORED);
        """;

    public const string ComputedColumnSqlServerDdl = """
        CREATE TABLE ComputedPerson (Id BIGINT IDENTITY(1,1) PRIMARY KEY, FirstName NVARCHAR(200) NOT NULL, LastName NVARCHAR(200) NOT NULL, FullName AS (FirstName + ' ' + LastName), [Base Value] INT NOT NULL, MixedCaseValue INT NOT NULL, [Computed Total] AS ([Base Value] + [MixedCaseValue]));
        """;

    public const string ComputedColumnMySqlDdl = """
        CREATE TABLE ComputedPerson (Id BIGINT AUTO_INCREMENT PRIMARY KEY, FirstName VARCHAR(200) NOT NULL, LastName VARCHAR(200) NOT NULL, FullName VARCHAR(401) GENERATED ALWAYS AS (CONCAT(FirstName, ' ', LastName)) STORED, `Base Value` INT NOT NULL, `MixedCaseValue` INT NOT NULL, `Computed Total` INT GENERATED ALWAYS AS (`Base Value` + `MixedCaseValue`) STORED);
        """;

    public const string ComputedColumnOracleDdl = """
        CREATE TABLE ComputedPerson (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, FirstName VARCHAR2(200) NOT NULL, LastName VARCHAR2(200) NOT NULL, FullName VARCHAR2(401) GENERATED ALWAYS AS (FirstName || ' ' || LastName), "Base Value" NUMBER(10) NOT NULL, MixedCaseValue NUMBER(10) NOT NULL, "Computed Total" NUMBER(10) GENERATED ALWAYS AS ("Base Value" + MixedCaseValue));
        """;

    // ---------------------------------------------------------------------------
    // JsonPath integration table: JsonPathDoc (a plain string column holding JSON).
    // ---------------------------------------------------------------------------

    public const string JsonPathSqliteDdl =
        "CREATE TABLE JsonPathDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, Data TEXT NOT NULL);";

    public const string JsonPathPostgreSqlDdl = """
        CREATE TABLE "JsonPathDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" TEXT NOT NULL, "Data" TEXT NOT NULL);
        """;

    public const string JsonPathSqlServerDdl = """
        CREATE TABLE JsonPathDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, Data NVARCHAR(MAX) NOT NULL);
        """;

    public const string JsonPathMySqlDdl = """
        CREATE TABLE JsonPathDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(200) NOT NULL, Data VARCHAR(4000) NOT NULL);
        """;

    public const string JsonPathOracleDdl = """
        CREATE TABLE JsonPathDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR2(200) NOT NULL, Data VARCHAR2(4000) NOT NULL);
        """;

    // ---------------------------------------------------------------------------
    // ViewEntity integration tables: Sale (base table) + v_CategoryTotals (VIEW).
    // ---------------------------------------------------------------------------

    public const string ViewEntitySqliteDdl = """
        CREATE TABLE Sale (Id INTEGER PRIMARY KEY AUTOINCREMENT, Category TEXT NOT NULL, Amount NUMERIC NOT NULL);
        CREATE VIEW v_CategoryTotals AS SELECT Category, COUNT(*) AS SaleCount, SUM(Amount) AS TotalAmount FROM Sale GROUP BY Category;
        """;

    public const string ViewEntityPostgreSqlDdl = """
        CREATE TABLE "Sale" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Category" TEXT NOT NULL, "Amount" NUMERIC NOT NULL);
        CREATE VIEW "v_CategoryTotals" AS SELECT "Category", COUNT(*)::INT AS "SaleCount", SUM("Amount") AS "TotalAmount" FROM "Sale" GROUP BY "Category";
        """;

    public const string ViewEntitySqlServerDdl = """
        CREATE TABLE Sale (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Category NVARCHAR(200) NOT NULL, Amount DECIMAL(18,2) NOT NULL);
        EXEC(N'CREATE VIEW v_CategoryTotals AS SELECT Category, COUNT(*) AS SaleCount, SUM(Amount) AS TotalAmount FROM Sale GROUP BY Category;');
        """;

    public const string ViewEntityMySqlDdl = """
        CREATE TABLE Sale (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Category VARCHAR(200) NOT NULL, Amount DECIMAL(18,2) NOT NULL);
        CREATE VIEW v_CategoryTotals AS SELECT Category, COUNT(*) AS SaleCount, SUM(Amount) AS TotalAmount FROM Sale GROUP BY Category;
        """;

    public const string ViewEntityOracleDdl = """
        CREATE TABLE Sale (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Category VARCHAR2(200) NOT NULL, Amount NUMBER(18,2) NOT NULL);
        CREATE VIEW v_CategoryTotals AS SELECT Category, COUNT(*) AS SaleCount, SUM(Amount) AS TotalAmount FROM Sale GROUP BY Category;
        """;

    // ---------------------------------------------------------------------------
    // BulkAllTypes: one column per provider-primitive for #134 all-types bulk-insert.
    // ---------------------------------------------------------------------------

    public const string BulkAllTypesSqliteDdl =
        "CREATE TABLE BulkAllTypesItem (Id INTEGER NOT NULL PRIMARY KEY, IntVal INTEGER NOT NULL, DecimalVal NUMERIC NOT NULL, BoolVal INTEGER NOT NULL, GuidVal TEXT NOT NULL, DateTimeVal TEXT NOT NULL, StringVal TEXT NOT NULL, NullableStringVal TEXT NULL, BinaryVal BLOB NOT NULL, EnumVal INTEGER NOT NULL, ConvertedVal NUMERIC NOT NULL);";

    public const string BulkAllTypesPostgreSqlDdl = """
        CREATE TABLE "BulkAllTypesItem" ("Id" INTEGER NOT NULL PRIMARY KEY, "IntVal" INTEGER NOT NULL, "DecimalVal" NUMERIC(18,2) NOT NULL, "BoolVal" BOOLEAN NOT NULL, "GuidVal" UUID NOT NULL, "DateTimeVal" TIMESTAMP NOT NULL, "StringVal" VARCHAR(200) NOT NULL, "NullableStringVal" VARCHAR(200) NULL, "BinaryVal" BYTEA NOT NULL, "EnumVal" INTEGER NOT NULL, "ConvertedVal" NUMERIC(18,2) NOT NULL)
        """;

    public const string BulkAllTypesSqlServerDdl =
        "CREATE TABLE [BulkAllTypesItem] ([Id] INT NOT NULL PRIMARY KEY, [IntVal] INT NOT NULL, [DecimalVal] DECIMAL(18,2) NOT NULL, [BoolVal] BIT NOT NULL, [GuidVal] UNIQUEIDENTIFIER NOT NULL, [DateTimeVal] DATETIME2 NOT NULL, [StringVal] NVARCHAR(200) NOT NULL, [NullableStringVal] NVARCHAR(200) NULL, [BinaryVal] VARBINARY(MAX) NOT NULL, [EnumVal] INT NOT NULL, [ConvertedVal] DECIMAL(18,2) NOT NULL);";

    public const string BulkAllTypesMySqlDdl =
        "CREATE TABLE BulkAllTypesItem (Id INT NOT NULL PRIMARY KEY, IntVal INT NOT NULL, DecimalVal DECIMAL(18,2) NOT NULL, BoolVal TINYINT(1) NOT NULL, GuidVal CHAR(36) NOT NULL, DateTimeVal DATETIME(6) NOT NULL, StringVal VARCHAR(200) NOT NULL, NullableStringVal VARCHAR(200) NULL, BinaryVal LONGBLOB NOT NULL, EnumVal INT NOT NULL, ConvertedVal DECIMAL(18,2) NOT NULL);";

    public const string BulkAllTypesOracleDdl =
        "CREATE TABLE BulkAllTypesItem (Id NUMBER(10) NOT NULL PRIMARY KEY, IntVal NUMBER(10) NOT NULL, DecimalVal NUMBER(18,2) NOT NULL, BoolVal NUMBER(1) NOT NULL, GuidVal RAW(16) NOT NULL, DateTimeVal TIMESTAMP NOT NULL, StringVal VARCHAR2(200) NOT NULL, NullableStringVal VARCHAR2(200) NULL, BinaryVal BLOB NOT NULL, EnumVal NUMBER(10) NOT NULL, ConvertedVal NUMBER(18,2) NOT NULL)";
}
