namespace Inquiry.FeatureCatalog;

/// <summary>
/// Per-dialect DDL for the shared feature-catalog tables (<c>VersionedItem</c>, <c>SoftItem</c>,
/// <c>JsonDoc</c>, <c>BulkItem</c>). Mirrors <c>Inquiry.Northwind.NorthwindSchema</c>: one constant per provider, applied by
/// the dialect test harnesses via <c>CreateFromDdlAsync</c>. These tables are deliberately separate from
/// Northwind so the schema-fidelity guardrail (<c>ExpectedNorthwindSchema</c>) stays untouched.
/// </summary>
public static class FeatureSchema
{
    public const string SqliteDdl = """
        CREATE TABLE VersionedItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Title TEXT NOT NULL, Version INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE SoftItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Name TEXT NOT NULL, IsDeleted INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE JsonDoc (Id INTEGER PRIMARY KEY AUTOINCREMENT, Owner TEXT NOT NULL, Balance NUMERIC NOT NULL, Tags TEXT NULL);
        CREATE TABLE BulkItem (Id INTEGER PRIMARY KEY AUTOINCREMENT, Category TEXT NOT NULL, Amount NUMERIC NOT NULL, Note TEXT NULL);
        """;

    // PostgreSQL folds unquoted identifiers to lowercase, but Inquiry's generated SQL quotes them
    // (case-preserved), so every identifier must be quoted to match — same convention as NorthwindSchema.
    public const string PostgreSqlDdl = """
        CREATE TABLE "VersionedItem" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Title" TEXT NOT NULL, "Version" INTEGER NOT NULL DEFAULT 0);
        CREATE TABLE "SoftItem" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Name" TEXT NOT NULL, "IsDeleted" BOOLEAN NOT NULL DEFAULT FALSE);
        CREATE TABLE "JsonDoc" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Owner" TEXT NOT NULL, "Balance" NUMERIC NOT NULL, "Tags" TEXT NULL);
        CREATE TABLE "BulkItem" ("Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "Category" VARCHAR(100) NOT NULL, "Amount" NUMERIC(18,2) NOT NULL, "Note" VARCHAR(200) NULL);
        """;

    public const string SqlServerDdl = """
        CREATE TABLE VersionedItem (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Title NVARCHAR(200) NOT NULL, [Version] INT NOT NULL DEFAULT 0);
        CREATE TABLE SoftItem (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Name NVARCHAR(200) NOT NULL, IsDeleted BIT NOT NULL DEFAULT 0);
        CREATE TABLE JsonDoc (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Owner NVARCHAR(200) NOT NULL, Balance DECIMAL(18,2) NOT NULL, Tags NVARCHAR(MAX) NULL);
        CREATE TABLE BulkItem (Id BIGINT IDENTITY(1,1) PRIMARY KEY, Category NVARCHAR(100) NOT NULL, Amount DECIMAL(18,2) NOT NULL, Note NVARCHAR(200) NULL);
        """;

    public const string MySqlDdl = """
        CREATE TABLE VersionedItem (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Title VARCHAR(200) NOT NULL, Version INT NOT NULL DEFAULT 0);
        CREATE TABLE SoftItem (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Name VARCHAR(200) NOT NULL, IsDeleted TINYINT(1) NOT NULL DEFAULT 0);
        CREATE TABLE JsonDoc (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Owner VARCHAR(200) NOT NULL, Balance DECIMAL(18,2) NOT NULL, Tags VARCHAR(2000) NULL);
        CREATE TABLE BulkItem (Id BIGINT AUTO_INCREMENT PRIMARY KEY, Category VARCHAR(100) NOT NULL, Amount DECIMAL(18,2) NOT NULL, Note VARCHAR(200) NULL);
        """;

    // Oracle: identity columns (12c+), NUMBER(1) for bool. Identifiers are left UNQUOTED so Oracle folds
    // them to uppercase, matching Inquiry's unquoted Oracle SQL generation (Version is not reserved).
    // Statements are split on ';' by the Oracle harness because Oracle rejects batched DDL in one command.
    public const string OracleDdl = """
        CREATE TABLE VersionedItem (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Title VARCHAR2(200) NOT NULL, Version NUMBER(10) DEFAULT 0 NOT NULL);
        CREATE TABLE SoftItem (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name VARCHAR2(200) NOT NULL, IsDeleted NUMBER(1) DEFAULT 0 NOT NULL);
        CREATE TABLE JsonDoc (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Owner VARCHAR2(200) NOT NULL, Balance NUMBER(18,2) NOT NULL, Tags VARCHAR2(2000) NULL);
        CREATE TABLE BulkItem (Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Category VARCHAR2(100) NOT NULL, Amount NUMBER(18,2) NOT NULL, Note VARCHAR2(200) NULL);
        """;
}
