<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <ProjectReference Include="..\..\src\Inquiry\Inquiry.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.Sqlite\Inquiry.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.SqlServer\Inquiry.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.PostgreSql\Inquiry.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.MySql\Inquiry.MySql.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.Oracle\Inquiry.Oracle.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.Generators.Shared\Inquiry.Generators.Shared.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.Sqlite.Analyzer\Inquiry.Sqlite.Analyzer.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.SqlServer.Analyzer\Inquiry.SqlServer.Analyzer.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.PostgreSql.Analyzer\Inquiry.PostgreSql.Analyzer.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.MySql.Analyzer\Inquiry.MySql.Analyzer.csproj" />
    <ProjectReference Include="..\..\src\Inquiry.Oracle.Analyzer\Inquiry.Oracle.Analyzer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
