using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Inquiry.Generators;

/// <summary>
/// Discovers <c>[InquiryAdHoc]</c> DTOs and emits a materializer per type. An ad-hoc DTO is a plain
/// result shape for hand-written <c>IInquiry.Query*</c> SQL — no table, key, or column attributes.
/// Every public instance property with a public/internal setter maps to one SELECT-list ordinal in
/// declaration order, so it reuses the same <see cref="MaterializerEmitter"/> as entities; the
/// materializer registers in DI exactly like an entity's, which is what the ad-hoc query path resolves.
/// </summary>
internal static class AdHocProcessor
{
    public static AdHocData Extract(INamedTypeSymbol symbol, CancellationToken cancellationToken)
    {
        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticData>();
        var location = symbol.Locations.FirstOrDefault();

        var columns = DiscoverColumns(symbol, cancellationToken);
        var isMapped = true;

        if (columns.Count == 0)
        {
            diagnostics.Add(DiagnosticData.Create(InquiryDiagnosticDescriptors.AdHocNoProperties, location, symbol.Name));
            isMapped = false;
        }

        // The materializer instantiates the DTO with an object initializer, so the type must be
        // concrete with an accessible parameterless constructor — a positional record's primary
        // constructor does not qualify.
        if (symbol.IsAbstract || !HasAccessibleParameterlessConstructor(symbol))
        {
            diagnostics.Add(DiagnosticData.Create(InquiryDiagnosticDescriptors.AdHocNotConstructible, location, symbol.Name));
            isMapped = false;
        }

        var classMaterializerName = symbol.Name + "InquiryAdHocMaterializer";
        var structMaterializerName = symbol.Name + "InquiryAdHocStructMaterializer";

        return new AdHocData(
            FullyQualifiedName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Name: symbol.Name,
            Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
            Columns: new EquatableArray<ColumnData>(columns.ToImmutableArray()),
            ClassMaterializerName: classMaterializerName,
            StructMaterializerName: structMaterializerName,
            ClassMaterializerFullName: GeneratorHelpers.GetGeneratedTypeName(symbol, classMaterializerName),
            IsMapped: isMapped,
            Diagnostics: new EquatableArray<DiagnosticData>(diagnostics.ToImmutable()));
    }

    public static EntityRegistration EmitMaterializer(SourceProductionContext context, AdHocData adHoc)
    {
        var adHocType = adHoc.FullyQualifiedName;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, adHoc.Namespace);

        source.AppendLine($"internal sealed class {adHoc.ClassMaterializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{adHocType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {adHocType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        MaterializerEmitter.EmitMaterializeBody(source, adHoc.Columns, adHocType, indent: "        ");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();

        source.AppendLine($"internal readonly struct {adHoc.StructMaterializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{adHocType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {adHocType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        MaterializerEmitter.EmitMaterializeBody(source, adHoc.Columns, adHocType, indent: "        ");
        source.AppendLine("    }");
        source.AppendLine("}");

        GeneratorHelpers.AppendNamespaceEnd(source, adHoc.Namespace);

        context.AddSource($"{adHoc.Name}.InquiryAdHoc.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new EntityRegistration(adHocType, adHoc.ClassMaterializerFullName);
    }

    private static List<ColumnData> DiscoverColumns(INamedTypeSymbol symbol, CancellationToken cancellationToken)
    {
        var columns = new List<ColumnData>();

        foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();
            // Ordinal mapping needs no per-property attributes: every public instance property
            // with a public/internal setter (set or init) maps, in declaration order. Get-only
            // (computed), static, indexer, and privately-settable properties are skipped and do
            // not occupy an ordinal. A record's synthesized EqualityContract is get-only, so it
            // is skipped here too.
            if (property.IsStatic || property.IsIndexer || property.SetMethod is null)
            {
                continue;
            }

            if (property.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal) ||
                property.SetMethod.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal))
            {
                continue;
            }

            var typeData = TypeData.Create(property.Type, property.NullableAnnotation);
            var enumAsString = typeData.IsEnum &&
                GeneratorHelpers.GetEntityAttribute(property, "InquiryEnumAsStringAttribute") is not null;

            // Only the fields MaterializerEmitter reads are populated (ad-hoc DTOs never feed DDL
            // or mutations); the column name is irrelevant to ordinal reads.
            columns.Add(new ColumnData
            {
                PropertyName = property.Name,
                ColumnName = property.Name,
                Type = typeData,
                EnumAsString = enumAsString,
            });
        }

        return columns;
    }

    private static bool HasAccessibleParameterlessConstructor(INamedTypeSymbol symbol)
    {
        foreach (var constructor in symbol.InstanceConstructors)
        {
            if (constructor.Parameters.Length == 0 &&
                constructor.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal or Accessibility.ProtectedOrInternal)
            {
                return true;
            }
        }

        return false;
    }
}
