using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Inquiry.Generators;

/// <summary>
/// Discovers <c>[InquiryTable]</c> entities and emits a materializer per entity. Discovery runs in
/// the syntax-provider transform and produces a value-equatable <see cref="EntityData"/> (carrying
/// diagnostics as data); emission consumes that data with no symbols, so the output stage caches.
/// </summary>
internal static class EntityProcessor
{
    /// <summary>Extracts the cacheable model for one <c>[InquiryTable]</c> entity symbol.</summary>
    public static EntityData Extract(INamedTypeSymbol entitySymbol, CancellationToken cancellationToken)
    {
        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticData>();
        var location = entitySymbol.Locations.FirstOrDefault();

        var tableAttribute = GeneratorHelpers.GetEntityAttribute(entitySymbol, "InquiryTableAttribute");
        var tableName = (tableAttribute is not null ? GeneratorHelpers.GetConstructorString(tableAttribute) : null) ?? entitySymbol.Name;
        var schema = tableAttribute is not null ? GeneratorHelpers.GetNamedString(tableAttribute, "Schema") : null;

        var columns = DiscoverColumns(entitySymbol, diagnostics);
        var relations = DiscoverRelations(entitySymbol, cancellationToken);

        var keyColumns = columns.Where(static c => c.IsKey).ToImmutableArray();
        var isMapped = true;

        if (keyColumns.Length == 0)
        {
            diagnostics.Add(DiagnosticData.Create(InquiryDiagnosticDescriptors.EntityKeyCount, location, entitySymbol.Name));
            isMapped = false;
        }
        else if (keyColumns.Length > 1)
        {
            var generatedKey = keyColumns.FirstOrDefault(static k => k.IsGenerated);
            if (generatedKey is not null)
            {
                diagnostics.Add(DiagnosticData.Create(InquiryDiagnosticDescriptors.CompositeKeyContainsGenerated, location, entitySymbol.Name, generatedKey.PropertyName));
                isMapped = false;
            }
        }

        foreach (var duplicate in columns.GroupBy(static c => c.ColumnName, StringComparer.OrdinalIgnoreCase).Where(static g => g.Count() > 1))
        {
            diagnostics.Add(DiagnosticData.Create(InquiryDiagnosticDescriptors.DuplicateColumn, location, entitySymbol.Name, duplicate.Key));
        }

        var classMaterializerName = entitySymbol.Name + "InquiryEntityMaterializer";
        var structMaterializerName = entitySymbol.Name + "InquiryEntityStructMaterializer";

        return new EntityData(
            FullyQualifiedName: entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Name: entitySymbol.Name,
            Namespace: entitySymbol.ContainingNamespace.IsGlobalNamespace ? null : entitySymbol.ContainingNamespace.ToDisplayString(),
            TableName: tableName,
            Schema: schema,
            Columns: new EquatableArray<ColumnData>(columns.ToImmutableArray()),
            Keys: new EquatableArray<ColumnData>(keyColumns),
            Relations: new EquatableArray<RelationData>(relations.ToImmutableArray()),
            ClassMaterializerName: classMaterializerName,
            StructMaterializerName: structMaterializerName,
            ClassMaterializerFullName: GeneratorHelpers.GetGeneratedTypeName(entitySymbol, classMaterializerName),
            StructMaterializerFullName: GeneratorHelpers.GetGeneratedTypeName(entitySymbol, structMaterializerName),
            IsMapped: isMapped,
            Diagnostics: new EquatableArray<DiagnosticData>(diagnostics.ToImmutable()));
    }

    public static EntityRegistration EmitMaterializer(SourceProductionContext context, EntityData entity)
    {
        var entityType = entity.FullyQualifiedName;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, entity.Namespace);

        // Class materializer — registered as singleton in DI and used by ad-hoc IInquiry queries
        // that resolve the materializer at runtime.
        source.AppendLine($"internal sealed class {entity.ClassMaterializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{entityType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {entityType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        MaterializerEmitter.EmitMaterializeBody(source, entity.Columns, entityType, indent: "        ");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();

        // Struct materializer — used by generated stores via the struct-constrained pipeline
        // overloads. The struct has no fields; generated stores pass `default(...)`. The JIT
        // produces a separate specialization per TMaterializer so the read-loop call to
        // Materialize is inlined instead of dispatched through the interface.
        source.AppendLine($"internal readonly struct {entity.StructMaterializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{entityType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {entityType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        MaterializerEmitter.EmitMaterializeBody(source, entity.Columns, entityType, indent: "        ");
        source.AppendLine("    }");
        source.AppendLine("}");

        GeneratorHelpers.AppendNamespaceEnd(source, entity.Namespace);

        context.AddSource($"{entity.Name}.InquiryEntity.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new EntityRegistration(entityType, entity.ClassMaterializerFullName);
    }

    private static List<ColumnData> DiscoverColumns(INamedTypeSymbol entitySymbol, ImmutableArray<DiagnosticData>.Builder diagnostics)
    {
        var columns = new List<ColumnData>();

        foreach (var property in entitySymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var keyAttribute = GeneratorHelpers.GetEntityAttribute(property, "InquiryKeyAttribute");
            var columnAttribute = keyAttribute ?? GeneratorHelpers.GetEntityAttribute(property, "InquiryColumnAttribute");
            var foreignKeyAttribute = GeneratorHelpers.GetEntityAttribute(property, "InquiryForeignKeyAttribute");
            if (columnAttribute is null && foreignKeyAttribute is null)
            {
                continue;
            }

            var columnName = ResolveColumnName(columnAttribute, foreignKeyAttribute, property.Name);
            var typeData = TypeData.Create(property.Type, property.NullableAnnotation);
            var isGenerated = keyAttribute is not null && GeneratorHelpers.GetNamedBool(keyAttribute, "IsGenerated");
            var useDatabaseDefault =
                columnAttribute is not null && GeneratorHelpers.GetNamedBool(columnAttribute, "UseDatabaseDefault") ||
                foreignKeyAttribute is not null && GeneratorHelpers.GetNamedBool(foreignKeyAttribute, "UseDatabaseDefault");
            columns.Add(new ColumnData
            {
                PropertyName = property.Name,
                ColumnName = columnName,
                Type = typeData,
                IsKey = keyAttribute is not null,
                IsGenerated = isGenerated,
                UseDatabaseDefault = useDatabaseDefault,
            });

            if (property.SetMethod is null || property.SetMethod.DeclaredAccessibility == Accessibility.Private)
            {
                diagnostics.Add(DiagnosticData.Create(
                    InquiryDiagnosticDescriptors.PropertyMustHavePublicSetter,
                    property.Locations.FirstOrDefault(),
                    entitySymbol.Name,
                    property.Name));
            }
        }

        return columns;
    }

    private static List<RelationData> DiscoverRelations(INamedTypeSymbol entitySymbol, CancellationToken cancellationToken)
    {
        var relations = new List<RelationData>();

        foreach (var property in entitySymbol.GetMembers().OfType<IPropertySymbol>())
        {
            cancellationToken.ThrowIfCancellationRequested();

            var relationAttribute = GeneratorHelpers.GetEntityAttribute(property, "InquiryRelationAttribute");
            if (relationAttribute is null)
            {
                continue;
            }

            var foreignKeyProperty = GeneratorHelpers.GetConstructorString(relationAttribute);
            if (string.IsNullOrEmpty(foreignKeyProperty))
            {
                continue;
            }

            // Determine child entity type. Supports List<T>, IReadOnlyList<T>, IEnumerable<T>, or T? directly.
            if (!TryGetChildEntityType(property.Type, out var childEntitySymbol, out var isCollection))
            {
                continue;
            }

            relations.Add(new RelationData(
                property.Name,
                foreignKeyProperty!,
                childEntitySymbol!.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                isCollection));
        }

        return relations;
    }

    private static bool TryGetChildEntityType(ITypeSymbol type, out INamedTypeSymbol? childEntitySymbol, out bool isCollection)
    {
        isCollection = false;
        childEntitySymbol = null;

        // Strip nullable wrapper first
        var nonNullable = type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } named
            ? named.TypeArguments[0]
            : type;

        if (nonNullable is INamedTypeSymbol namedType)
        {
            if (namedType.IsGenericType && namedType.TypeArguments.Length == 1)
            {
                var fqn = namedType.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                if (fqn is "global::System.Collections.Generic.List<T>"
                         or "global::System.Collections.Generic.IReadOnlyList<T>"
                         or "global::System.Collections.Generic.IList<T>"
                         or "global::System.Collections.Generic.IEnumerable<T>"
                         or "global::System.Collections.Generic.ICollection<T>")
                {
                    childEntitySymbol = namedType.TypeArguments[0] as INamedTypeSymbol;
                    isCollection = true;
                    return childEntitySymbol is not null;
                }
            }

            // Single reference
            childEntitySymbol = namedType;
            isCollection = false;
            return true;
        }

        return false;
    }

    private static string ResolveColumnName(AttributeData? columnAttribute, AttributeData? foreignKeyAttribute, string propertyName)
    {
        if (columnAttribute is not null)
        {
            return GeneratorHelpers.GetConstructorString(columnAttribute) ?? propertyName;
        }

        // Foreign-key attribute. The 3-arg form (localColumn, referencedTable, referencedColumn)
        // supplies an explicit column name at index 0; the 2-arg form defaults to the property name.
        if (foreignKeyAttribute is { ConstructorArguments.Length: 3 } &&
            foreignKeyAttribute.ConstructorArguments[0].Value is string explicitColumn &&
            !string.IsNullOrWhiteSpace(explicitColumn))
        {
            return explicitColumn;
        }

        return propertyName;
    }

}
