using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// W5b: discovers <c>[InquiryProjection(typeof(Entity))]</c> result types and emits a materializer per
/// projection. A projection is a flat, read-only subset of an entity's columns (no key/relations); its
/// materializer reads each column by its position in the projected SELECT list, so it reuses the same
/// <see cref="MaterializerEmitter"/> as entities.
/// </summary>
internal static class ProjectionProcessor
{
    public static ProjectionData Extract(INamedTypeSymbol symbol)
    {
        var diagnostics = ImmutableArray.CreateBuilder<DiagnosticData>();
        var location = symbol.Locations.FirstOrDefault();

        var projectionAttribute = GeneratorHelpers.GetEntityAttribute(symbol, "InquiryProjectionAttribute");
        var entityFqn = projectionAttribute is { ConstructorArguments.Length: > 0 } &&
            projectionAttribute.ConstructorArguments[0].Value is INamedTypeSymbol entitySymbol
            ? entitySymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            : string.Empty;

        var columns = DiscoverColumns(symbol);
        var isMapped = columns.Count > 0;
        if (!isMapped)
        {
            diagnostics.Add(DiagnosticData.Create(InquiryDiagnosticDescriptors.ProjectionNoColumns, location, symbol.Name));
        }

        var classMaterializerName = symbol.Name + "InquiryProjectionMaterializer";
        var structMaterializerName = symbol.Name + "InquiryProjectionStructMaterializer";

        return new ProjectionData(
            FullyQualifiedName: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Name: symbol.Name,
            Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
            EntityFullyQualifiedName: entityFqn,
            Columns: new EquatableArray<ColumnData>(columns.ToImmutableArray()),
            ClassMaterializerName: classMaterializerName,
            StructMaterializerName: structMaterializerName,
            ClassMaterializerFullName: GeneratorHelpers.GetGeneratedTypeName(symbol, classMaterializerName),
            StructMaterializerFullName: GeneratorHelpers.GetGeneratedTypeName(symbol, structMaterializerName),
            IsMapped: isMapped,
            Diagnostics: new EquatableArray<DiagnosticData>(diagnostics.ToImmutable()));
    }

    public static EntityRegistration EmitMaterializer(SourceProductionContext context, ProjectionData projection)
    {
        var projectionType = projection.FullyQualifiedName;

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, projection.Namespace);

        source.AppendLine($"internal sealed class {projection.ClassMaterializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{projectionType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {projectionType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        MaterializerEmitter.EmitMaterializeBody(source, projection.Columns, projectionType, indent: "        ");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();

        source.AppendLine($"internal readonly struct {projection.StructMaterializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{projectionType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {projectionType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        MaterializerEmitter.EmitMaterializeBody(source, projection.Columns, projectionType, indent: "        ");
        source.AppendLine("    }");
        source.AppendLine("}");

        GeneratorHelpers.AppendNamespaceEnd(source, projection.Namespace);

        context.AddSource($"{projection.Name}.InquiryProjection.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new EntityRegistration(projectionType, projection.ClassMaterializerFullName);
    }

    private static List<ColumnData> DiscoverColumns(INamedTypeSymbol symbol)
    {
        var columns = new List<ColumnData>();

        foreach (var property in symbol.GetMembers().OfType<IPropertySymbol>())
        {
            var columnAttribute = GeneratorHelpers.GetEntityAttribute(property, "InquiryColumnAttribute");
            if (columnAttribute is null)
            {
                continue;
            }

            var columnName = GeneratorHelpers.GetConstructorString(columnAttribute) ?? property.Name;
            var typeData = TypeData.Create(property.Type, property.NullableAnnotation);
            var enumAsString = typeData.IsEnum &&
                GeneratorHelpers.GetEntityAttribute(property, "InquiryEnumAsStringAttribute") is not null;

            // Only the fields MaterializerEmitter reads are populated (projections never feed DDL or
            // mutations); the rest default.
            columns.Add(new ColumnData
            {
                PropertyName = property.Name,
                ColumnName = columnName,
                Type = typeData,
                EnumAsString = enumAsString,
            });
        }

        return columns;
    }
}
