using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// Emits the DI registration class and the public extension method that registers it explicitly.
/// </summary>
internal static class RegistrationEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<EntityRegistration> entityRegistrations,
        ImmutableArray<StoreRegistration> storeRegistrations)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("namespace Inquiry.DependencyInjection");
        source.AppendLine("{");
        source.AppendLine("    public static class InquiryGeneratedServiceCollectionExtensions");
        source.AppendLine("    {");
        source.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddInquiryGeneratedStores(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("        {");
        source.AppendLine("            new global::Inquiry.Generated.InquiryGeneratedServiceRegistration().AddServices(services);");
        source.AppendLine("            return services;");
        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine("namespace Inquiry.Generated");
        source.AppendLine("{");
        source.AppendLine("    internal sealed class InquiryGeneratedServiceRegistration : global::Inquiry.DependencyInjection.IInquiryServiceRegistration");
        source.AppendLine("    {");
        source.AppendLine("        public void AddServices(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        source.AppendLine("        {");
        source.AppendLine("            if (services is null)");
        source.AppendLine("            {");
        source.AppendLine("                throw new global::System.ArgumentNullException(nameof(services));");
        source.AppendLine("            }");
        source.AppendLine();

        foreach (var registration in entityRegistrations)
        {
            source.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Inquiry.Materialization.IInquiryEntityMaterializer<{registration.EntityFullyQualifiedName}>, {registration.MaterializerFullName}>(services);");
        }

        foreach (var registration in storeRegistrations)
        {
            // Stores are scoped to align with IInquiry's lifetime: one store instance per
            // request/scope, reused across every call in that scope, but never shared across
            // scopes (so each store sees the scope-local IInquiry). The store itself is
            // stateless after construction (all SQL is in const fields), so scoping is purely
            // about the captured IInquiry reference.
            source.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<{registration.StoreFullyQualifiedName}>(services);");
        }

        source.AppendLine("        }");
        source.AppendLine("    }");
        source.AppendLine("}");

        context.AddSource("InquiryGeneratedServiceRegistration.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
