using Inquiry.Generators.Abstractions;
using Inquiry.Generators.Diagnostics;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// Emits a per-assembly <c>InquiryGeneratedSchema.g.cs</c> exposing the full <c>CREATE TABLE</c>
/// DDL for every mapped entity as a single <c>const string</c>. Tables are ordered so a referenced
/// table is created before the table that references it (topological sort over foreign keys; self
/// references and cross-assembly references do not constrain ordering).
/// </summary>
/// <remarks>
/// DDL generation only. ALTER/diff, versioning, a history table, and an apply runner are out
/// of scope — feed <see cref="Ddl"/> into a migration runner (e.g. DbUp) as the initial script, or use
/// it for first-run/dev table creation.
/// </remarks>
internal static class SchemaEmitter
{
    public const string GeneratedClassName = "InquiryGeneratedSchema";
    private const string GeneratedNamespace = "Inquiry.Generated";

    public static void Emit(SourceProductionContext context, IReadOnlyList<EntityData> entities, SqlBuilder builder)
    {
        if (entities.Count == 0)
        {
            return;
        }

        // A string foreign-key column with no declared Length inherits its referenced column's declared
        // Length, so on a bounded dialect it emits a valid bounded VARCHAR instead of an unindexable/
        // unkeyable LOB. Indexed by (table, column) across every entity (the referenced table may be any).
        var declaredLengths = BuildColumnLengthIndex(entities);

        ReportKeyDiagnostics(context, entities, builder, declaredLengths);

        var ordered = OrderByForeignKeyDependencies(entities);

        var ddl = new StringBuilder();
        // Index statements are collected and appended after every CREATE TABLE so a referenced table
        // always exists before its index is created.
        var indexStatements = new List<string>();
        for (var i = 0; i < ordered.Count; i++)
        {
            if (i > 0)
            {
                ddl.Append("\n\n");
            }

            var entity = ordered[i];
            var columns = ResolveColumns(entity, declaredLengths);
            var ctx = new SqlBuildContext(
                builder,
                entity.Schema,
                entity.TableName,
                columns,
                suppressSoftDelete: false,
                generateForeignKeys: entity.GenerateForeignKeys);
            ddl.Append(builder.BuildCreateTableSql(ctx));
            ddl.Append(';');
            indexStatements.AddRange(builder.BuildCreateIndexSql(ctx));
        }

        foreach (var indexStatement in indexStatements)
        {
            ddl.Append("\n\n").Append(indexStatement).Append(';');
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();
        source.AppendLine("/// <summary>Generated CREATE TABLE DDL for every Inquiry entity in this assembly.</summary>");
        // internal (not public): each assembly emits its own copy, so a referencing assembly that also
        // uses Inquiry does not collide on a single public Inquiry.Generated.InquiryGeneratedSchema type.
        source.AppendLine($"internal static class {GeneratedClassName}");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>The full schema DDL, tables ordered so referenced tables precede their dependents.</summary>");
        source.AppendLine($"    public const string Ddl = @\"{ddl.ToString().Replace("\"", "\"\"")}\";");
        source.AppendLine("}");

        context.AddSource($"{GeneratedClassName}.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Reports generation-time errors for key columns that would produce invalid DDL — a
    /// database-generated key that is not an integer (INQ030), and an unbounded string key on a dialect
    /// that cannot key on unbounded text (INQ031). Location-less (the cached model carries no symbol).
    /// </summary>
    private static void ReportKeyDiagnostics(SourceProductionContext context, IReadOnlyList<EntityData> entities, SqlBuilder builder, Dictionary<string, int> declaredLengths)
    {
        foreach (var entity in entities)
        {
            foreach (var key in entity.Keys.AsImmutableArray())
            {
                if (key.IsGenerated && !IsIntegerClass(key.TypeClass))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        InquiryDiagnosticDescriptors.GeneratedKeyNotInteger, location: null, entity.TableName, key.PropertyName));
                }
                else if (key.TypeClass == DbTypeClass.String && key.Length == 0 && string.IsNullOrEmpty(key.SqlType) && builder.RequiresBoundedStringKeys)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        InquiryDiagnosticDescriptors.StringKeyRequiresLength, location: null, entity.TableName, key.PropertyName, builder.DialectName));
                }
            }

            // INQ032: a bounded dialect cannot index an unbounded string (it maps to CLOB / NVARCHAR(MAX)
            // / LONGTEXT), so the generator skips that index (see SqlBuilder.BuildCreateIndexSql). Warn so
            // the dropped index is not silent — an explicit Length has it created. Non-key only: a string
            // key is the INQ031 error, and a foreign key inherits its referenced key's Length below.
            if (!builder.RequiresBoundedStringKeys)
            {
                continue;
            }

            foreach (var column in entity.Columns.AsImmutableArray())
            {
                if ((column.IsIndexed || column.IsUnique) && !column.IsKey && IsUnboundedAfterDerivation(column, declaredLengths))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        InquiryDiagnosticDescriptors.IndexedStringRequiresLength, location: null, entity.TableName, column.PropertyName, builder.DialectName));
                }
            }
        }
    }

    private static bool IsIntegerClass(DbTypeClass typeClass)
        => typeClass is DbTypeClass.Byte or DbTypeClass.Int16 or DbTypeClass.Int32 or DbTypeClass.Int64;

    /// <summary>
    /// Kahn's topological sort keyed by table name (case-insensitive). Edges point from a referencing
    /// table to the table it references; an edge whose target is not in this assembly's entity set, or
    /// a self reference, is ignored. Input order is the tiebreak, and any rows left over by a reference
    /// cycle are appended in input order so emission is always total and deterministic.
    /// </summary>
    private static IReadOnlyList<EntityData> OrderByForeignKeyDependencies(IReadOnlyList<EntityData> entities)
    {
        var byTable = new Dictionary<string, EntityData>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var entity in entities)
        {
            byTable[entity.TableName] = entity;
        }

        // Dependencies: tables this entity references via a foreign key (within this assembly, excluding self).
        var dependencies = new Dictionary<EntityData, HashSet<string>>();
        foreach (var entity in entities)
        {
            var deps = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var column in entity.Columns.AsImmutableArray())
            {
                if (string.IsNullOrEmpty(column.ForeignKeyTable))
                {
                    continue;
                }

                if (!string.Equals(column.ForeignKeyTable, entity.TableName, System.StringComparison.OrdinalIgnoreCase)
                    && byTable.ContainsKey(column.ForeignKeyTable!))
                {
                    deps.Add(column.ForeignKeyTable!);
                }
            }

            dependencies[entity] = deps;
        }

        var ordered = new List<EntityData>(entities.Count);
        var emitted = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

        // Repeatedly emit every entity whose dependencies are all already emitted, preserving input
        // order within each pass. Stop when a pass adds nothing (all done, or a cycle remains).
        bool progress = true;
        while (progress && ordered.Count < entities.Count)
        {
            progress = false;
            foreach (var entity in entities)
            {
                if (emitted.Contains(entity.TableName))
                {
                    continue;
                }

                if (dependencies[entity].All(emitted.Contains))
                {
                    ordered.Add(entity);
                    emitted.Add(entity.TableName);
                    progress = true;
                }
            }
        }

        // Append anything left (reference cycle) in input order.
        foreach (var entity in entities)
        {
            if (!emitted.Contains(entity.TableName))
            {
                ordered.Add(entity);
                emitted.Add(entity.TableName);
            }
        }

        return ordered;
    }

    /// <summary>Indexes every declared (non-zero) column Length by (table, column) for FK derivation.</summary>
    private static Dictionary<string, int> BuildColumnLengthIndex(IReadOnlyList<EntityData> entities)
    {
        var map = new Dictionary<string, int>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var entity in entities)
        {
            foreach (var column in entity.Columns.AsImmutableArray())
            {
                if (column.Length > 0)
                {
                    map[ColumnKey(entity.TableName, column.ColumnName)] = column.Length;
                }
            }
        }

        return map;
    }

    // '\0' cannot appear in a SQL identifier, so it is a collision-proof composite-key separator
    // (identifiers may contain spaces, e.g. "Order Details").
    private static string ColumnKey(string table, string column) => table + "\0" + column;

    /// <summary>
    /// A non-key string foreign-key column with no declared <see cref="ColumnData.Length"/> (and no
    /// <see cref="ColumnData.SqlType"/>) inherits its referenced column's declared Length; everything else
    /// is returned unchanged. Keys are exempt — an unbounded string key is an explicit-Length error
    /// (INQ031), not silently derived.
    /// </summary>
    private static ColumnData DeriveForeignKeyLength(ColumnData column, Dictionary<string, int> declaredLengths)
    {
        if (column.Length == 0
            && !column.IsKey
            && column.TypeClass == DbTypeClass.String
            && string.IsNullOrEmpty(column.SqlType)
            && !string.IsNullOrEmpty(column.ForeignKeyTable)
            && !string.IsNullOrEmpty(column.ForeignKeyColumn)
            && declaredLengths.TryGetValue(ColumnKey(column.ForeignKeyTable!, column.ForeignKeyColumn!), out var referencedLength))
        {
            return column with { Length = referencedLength };
        }

        return column;
    }

    private static List<IColumn> ResolveColumns(EntityData entity, Dictionary<string, int> declaredLengths)
    {
        var list = new List<IColumn>(entity.Columns.Count);
        foreach (var column in entity.Columns.AsImmutableArray())
        {
            list.Add(DeriveForeignKeyLength(column, declaredLengths));
        }

        return list;
    }

    /// <summary>True for a string column that is still unbounded (TEXT/LOB/MAX) after FK-length derivation.</summary>
    private static bool IsUnboundedAfterDerivation(ColumnData column, Dictionary<string, int> declaredLengths)
        => column.TypeClass == DbTypeClass.String
           && string.IsNullOrEmpty(column.SqlType)
           && DeriveForeignKeyLength(column, declaredLengths).Length == 0;
}
