using Inquiry.Generators.Abstractions;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Inquiry.Generators;

/// <summary>
/// W7: emits a per-assembly <c>InquiryGeneratedSchema.g.cs</c> exposing the full <c>CREATE TABLE</c>
/// DDL for every mapped entity as a single <c>const string</c>. Tables are ordered so a referenced
/// table is created before the table that references it (topological sort over foreign keys; self
/// references and cross-assembly references do not constrain ordering).
/// </summary>
/// <remarks>
/// Phase A (DDL generation) only. ALTER/diff, versioning, a history table, and an apply runner are out
/// of scope — feed <see cref="Ddl"/> into a migration runner (e.g. DbUp) as the initial script, or use
/// it for first-run/dev table creation.
/// </remarks>
internal static class SchemaEmitter
{
    public const string GeneratedClassName = "InquiryGeneratedSchema";
    private const string GeneratedNamespace = "Inquiry.Generated";

    public static void Emit(SourceProductionContext context, IReadOnlyList<EntityData> entities, SqlBuilder builder)
    {
        if (entities.Count == 0)
        {
            return;
        }

        var ordered = OrderByForeignKeyDependencies(entities);

        var ddl = new StringBuilder();
        for (var i = 0; i < ordered.Count; i++)
        {
            if (i > 0)
            {
                ddl.Append("\n\n");
            }

            var entity = ordered[i];
            var columns = ToColumnList(entity.Columns);
            var ctx = new SqlBuildContext(
                builder,
                entity.Schema,
                entity.TableName,
                columns,
                suppressSoftDelete: false,
                generateForeignKeys: entity.GenerateForeignKeys);
            ddl.Append(builder.BuildCreateTableSql(ctx));
            ddl.Append(';');
        }

        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine($"namespace {GeneratedNamespace};");
        source.AppendLine();
        source.AppendLine("/// <summary>Generated CREATE TABLE DDL for every Inquiry entity in this assembly (W7 Phase A).</summary>");
        // internal (not public): each assembly emits its own copy, so a referencing assembly that also
        // uses Inquiry does not collide on a single public Inquiry.Generated.InquiryGeneratedSchema type.
        source.AppendLine($"internal static class {GeneratedClassName}");
        source.AppendLine("{");
        source.AppendLine("    /// <summary>The full schema DDL, tables ordered so referenced tables precede their dependents.</summary>");
        source.AppendLine($"    public const string Ddl = @\"{ddl.ToString().Replace("\"", "\"\"")}\";");
        source.AppendLine("}");

        context.AddSource($"{GeneratedClassName}.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    /// <summary>
    /// Kahn's topological sort keyed by table name (case-insensitive). Edges point from a referencing
    /// table to the table it references; an edge whose target is not in this assembly's entity set, or
    /// a self reference, is ignored. Input order is the tiebreak, and any rows left over by a reference
    /// cycle are appended in input order so emission is always total and deterministic.
    /// </summary>
    private static IReadOnlyList<EntityData> OrderByForeignKeyDependencies(IReadOnlyList<EntityData> entities)
    {
        var byTable = new Dictionary<string, EntityData>(System.StringComparer.OrdinalIgnoreCase);
        foreach (var entity in entities)
        {
            byTable[entity.TableName] = entity;
        }

        // Dependencies: tables this entity references via a foreign key (within this assembly, excluding self).
        var dependencies = new Dictionary<EntityData, HashSet<string>>();
        foreach (var entity in entities)
        {
            var deps = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            foreach (var column in entity.Columns.AsImmutableArray())
            {
                if (string.IsNullOrEmpty(column.ForeignKeyTable))
                {
                    continue;
                }

                if (!string.Equals(column.ForeignKeyTable, entity.TableName, System.StringComparison.OrdinalIgnoreCase)
                    && byTable.ContainsKey(column.ForeignKeyTable!))
                {
                    deps.Add(column.ForeignKeyTable!);
                }
            }

            dependencies[entity] = deps;
        }

        var ordered = new List<EntityData>(entities.Count);
        var emitted = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);

        // Repeatedly emit every entity whose dependencies are all already emitted, preserving input
        // order within each pass. Stop when a pass adds nothing (all done, or a cycle remains).
        bool progress = true;
        while (progress && ordered.Count < entities.Count)
        {
            progress = false;
            foreach (var entity in entities)
            {
                if (emitted.Contains(entity.TableName))
                {
                    continue;
                }

                if (dependencies[entity].All(emitted.Contains))
                {
                    ordered.Add(entity);
                    emitted.Add(entity.TableName);
                    progress = true;
                }
            }
        }

        // Append anything left (reference cycle) in input order.
        foreach (var entity in entities)
        {
            if (!emitted.Contains(entity.TableName))
            {
                ordered.Add(entity);
                emitted.Add(entity.TableName);
            }
        }

        return ordered;
    }

    private static List<IColumn> ToColumnList(EquatableArray<ColumnData> columns)
    {
        var list = new List<IColumn>(columns.Count);
        foreach (var column in columns.AsImmutableArray())
        {
            list.Add(column);
        }

        return list;
    }
}
