using System.Linq;
using System.Text;
using Inquiry.Generators.Infrastructure;
using Inquiry.Generators.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using GeneratorTypeInfo = Inquiry.Generators.Models.TypeInfo;

namespace Inquiry.Generators.Features.EntityMetadata;

internal static class EntityMetadataFeature
{
    public static EntityRegistrationModel Generate(SourceProductionContext context, EntityModel entity)
    {
        var metadataName = $"{entity.Symbol.Name}InquiryEntityMetadata";
        var materializerName = $"{entity.Symbol.Name}InquiryEntityMaterializer";
        var entityType = entity.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var keyIndex = entity.Columns.IndexOf(entity.Key);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        GeneratorHelpers.AppendNamespaceStart(source, entity.Symbol);
        source.AppendLine($"internal sealed class {metadataName} : global::Inquiry.Entities.IInquiryEntityMetadata<{entityType}>");
        source.AppendLine("{");
        source.AppendLine($"    public string TableName => \"{GeneratorHelpers.Escape(entity.TableName)}\";");
        source.AppendLine();
        source.AppendLine($"    public string? Schema => {GeneratorHelpers.Literal(entity.Schema)};");
        source.AppendLine();
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::Inquiry.Sql.InquirySqlColumn> Columns { get; } =");
        source.AppendLine("        new global::Inquiry.Sql.InquirySqlColumn[]");
        source.AppendLine("        {");
        foreach (var column in entity.Columns)
        {
            source.AppendLine($"            new global::Inquiry.Sql.InquirySqlColumn(\"{GeneratorHelpers.Escape(column.PropertyName)}\", \"{GeneratorHelpers.Escape(column.ColumnName)}\", isKey: {GeneratorHelpers.BooleanLiteral(column.IsKey)}, isGenerated: {GeneratorHelpers.BooleanLiteral(column.IsGenerated)}),");
        }

        source.AppendLine("        };");
        source.AppendLine();
        source.AppendLine($"    public global::Inquiry.Sql.InquirySqlColumn Key => Columns[{keyIndex}];");
        source.AppendLine();
        source.AppendLine("    public global::System.Collections.Generic.IReadOnlyList<global::Inquiry.Entities.InquiryForeignKey> ForeignKeys { get; } =");
        if (entity.Columns.Any(static c => c.ForeignKey is not null))
        {
            source.AppendLine("        new global::Inquiry.Entities.InquiryForeignKey[]");
            source.AppendLine("        {");
            foreach (var column in entity.Columns.Where(static c => c.ForeignKey is not null))
            {
                source.AppendLine($"            new global::Inquiry.Entities.InquiryForeignKey(\"{GeneratorHelpers.Escape(column.PropertyName)}\", \"{GeneratorHelpers.Escape(column.ColumnName)}\", \"{GeneratorHelpers.Escape(column.ForeignKey!.ReferencedTable)}\", \"{GeneratorHelpers.Escape(column.ForeignKey.ReferencedColumn)}\"),");
            }

            source.AppendLine("        };");
        }
        else
        {
            source.AppendLine("        global::System.Array.Empty<global::Inquiry.Entities.InquiryForeignKey>();");
        }

        source.AppendLine("}");
        source.AppendLine();
        source.AppendLine($"internal sealed class {materializerName} : global::Inquiry.Materialization.IInquiryEntityMaterializer<{entityType}>");
        source.AppendLine("{");
        source.AppendLine($"    public {entityType} Materialize(global::System.Data.Common.DbDataReader reader)");
        source.AppendLine("    {");
        source.AppendLine($"        return new {entityType}");
        source.AppendLine("        {");
        for (var i = 0; i < entity.Columns.Count; i++)
        {
            var column = entity.Columns[i];
            source.AppendLine($"            {column.PropertyName} = {ReadExpression(column.Type, i)},");
        }

        source.AppendLine("        };");
        source.AppendLine("    }");
        source.AppendLine("}");
        GeneratorHelpers.AppendNamespaceEnd(source, entity.Symbol);

        context.AddSource($"{entity.Symbol.Name}.InquiryEntity.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        return new EntityRegistrationModel(entity.Symbol, metadataName, materializerName);
    }

    private static string ReadExpression(GeneratorTypeInfo type, int index)
    {
        var nonNullable = type.NonNullableDisplayName;
        var read = type.SpecialType switch
        {
            SpecialType.System_String => $"reader.GetString({index})",
            SpecialType.System_Boolean => $"reader.GetBoolean({index})",
            SpecialType.System_Int16 => $"reader.GetInt16({index})",
            SpecialType.System_Int32 => $"reader.GetInt32({index})",
            SpecialType.System_Int64 => $"reader.GetInt64({index})",
            SpecialType.System_Single => $"reader.GetFloat({index})",
            SpecialType.System_Double => $"reader.GetDouble({index})",
            SpecialType.System_Decimal => $"reader.GetDecimal({index})",
            SpecialType.System_DateTime => $"reader.GetDateTime({index})",
            _ when type.IsGuid => $"reader.GetGuid({index})",
            _ => $"reader.GetFieldValue<{nonNullable}>({index})",
        };

        if (!type.IsNullable)
        {
            return read;
        }

        if (type.Symbol.IsValueType)
        {
            return $"reader.IsDBNull({index}) ? ({type.DisplayName})null : {read}";
        }

        return $"reader.IsDBNull({index}) ? null : {read}";
    }
}
