using Inquiry.Entities;
using Inquiry.Oracle.Tests.Fixtures;
using Inquiry.Stores;

namespace Inquiry.Oracle.Tests;

[InquiryTable("OraKeyOnlyItem")]
public sealed class OraKeyOnlyItem
{
    [InquiryKey]
    public int Id { get; set; }
}

public partial class OraKeyOnlyItemStore : InquiryStore<OraKeyOnlyItem>
{
    [InquiryUpsert]
    public partial Task<int> UpsertAsync(OraKeyOnlyItem item, CancellationToken cancellationToken = default);

    [InquirySelectAll]
    public partial Task<IReadOnlyList<OraKeyOnlyItem>> AllAsync(CancellationToken cancellationToken = default);
}

[Collection(OracleCollection.Name)]
public sealed class EmptyUpsertSetIntegrationTests
{
    private readonly OracleContainerFixture _fixture;

    public EmptyUpsertSetIntegrationTests(OracleContainerFixture fixture) => _fixture = fixture;

    private const string Ddl = """
        CREATE TABLE OraKeyOnlyItem (Id NUMBER(10) PRIMARY KEY);
        CREATE TABLE OraGeneratedKeyOnlyItem (Id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);
        CREATE TABLE OraDefaultKeyOnlyItem (Id VARCHAR2(32) DEFAULT LOWER(RAWTOHEX(SYS_GUID())) PRIMARY KEY)
        """;

    [SkippableFact]
    public async Task ClientKeyOnlyEntityMergeHandlesEmptyUpdateSet()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "key_only");
        var store = harness.GetRequiredService<OraKeyOnlyItemStore>();
        var item = new OraKeyOnlyItem { Id = 42 };

        await store.UpsertAsync(item);
        await store.UpsertAsync(item);

        var stored = Assert.Single(await store.AllAsync());
        Assert.Equal(42, stored.Id);
    }

    [SkippableFact]
    public async Task GeneratedKeyUpsertUsesGeneratedUnsupportedContract()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "generated_key");
        var store = harness.GetRequiredService<OraGeneratedKeyOnlyItemStore>();

        var failure = await Assert.ThrowsAsync<NotSupportedException>(() =>
            store.UpsertAsync(new OraGeneratedKeyOnlyItem()));

        Assert.Contains("database-generated", failure.Message, StringComparison.OrdinalIgnoreCase);
    }

    [SkippableFact]
    public async Task DefaultKeyUpsertUsesGeneratedUnsupportedContract()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "default_key");
        var store = harness.GetRequiredService<OraDefaultKeyOnlyItemStore>();

        var failure = await Assert.ThrowsAsync<NotSupportedException>(() =>
            store.UpsertAsync(new OraDefaultKeyOnlyItem()));

        Assert.Contains("database-generated", failure.Message, StringComparison.OrdinalIgnoreCase);
    }
}
