using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Inquiry.Entities;
using Inquiry.Oracle.Tests.Fixtures;
using Inquiry.Stores;

namespace Inquiry.Oracle.Tests;

[InquiryTable("OraKeyOnlyItem")]
public sealed class OraKeyOnlyItem
{
    [InquiryKey(IsGenerated = true)]
    public int? Id { get; set; }
}

public partial class OraKeyOnlyItemStore : InquiryStore<OraKeyOnlyItem>
{
    [InquiryUpsert]
    public partial Task<int> UpsertAsync(OraKeyOnlyItem item, CancellationToken ct = default);

    [InquirySelectAll]
    public partial Task<IReadOnlyList<OraKeyOnlyItem>> AllAsync(CancellationToken ct = default);
}

[Collection(OracleCollection.Name)]
public sealed class EmptyUpsertSetIntegrationTests
{
    private readonly OracleContainerFixture _fixture;
    public EmptyUpsertSetIntegrationTests(OracleContainerFixture fixture) => _fixture = fixture;

    private const string Ddl = "CREATE TABLE OraKeyOnlyItem (Id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)";

    [SkippableFact]
    public async Task KeyOnlyEntityMergeHandlesEmptyUpdateSet()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "keyonly");
        var store = harness.GetRequiredService<OraKeyOnlyItemStore>();

        await store.UpsertAsync(new OraKeyOnlyItem { Id = null });
        var id = Assert.Single(await store.AllAsync()).Id;
        Assert.NotNull(id);

        await store.UpsertAsync(new OraKeyOnlyItem { Id = id });
        Assert.Single(await store.AllAsync());
    }
}
