using Inquiry.Northwind.Models;
using Inquiry.Northwind.Stores;
using Inquiry.Oracle.Tests.Fixtures;

namespace Inquiry.Oracle.Tests;

/// <summary>
/// End-to-end test of multi-field select on Oracle. Uses a minimal DDL without foreign keys
/// so Orders can be inserted without parent Customers/Employees/Shippers.
/// </summary>
[Collection(OracleCollection.Name)]
public sealed class MultiFieldSelectIntegrationTests
{
    /// <summary>
    /// Minimal Orders table DDL with no foreign key constraints.
    /// Column types mirror <see cref="Inquiry.Northwind.NorthwindSchema.OracleDdl"/>.
    /// </summary>
    private const string Ddl = """
        CREATE TABLE Orders (
            OrderID         NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            CustomerID      VARCHAR2(5),
            EmployeeID      NUMBER(10),
            OrderDate       TIMESTAMP,
            RequiredDate    TIMESTAMP,
            ShippedDate     TIMESTAMP,
            ShipVia         NUMBER(10),
            Freight         NUMBER(19,4) DEFAULT 0,
            ShipName        VARCHAR2(40),
            ShipAddress     VARCHAR2(120),
            ShipCity        VARCHAR2(60),
            ShipRegion      VARCHAR2(60),
            ShipPostalCode  VARCHAR2(20),
            ShipCountry     VARCHAR2(60)
        )
        """;

    private readonly OracleContainerFixture _fixture;
    public MultiFieldSelectIntegrationTests(OracleContainerFixture fixture) => _fixture = fixture;

    [SkippableFact]
    public async Task SelectByTwoFieldsReturnsOnlyRowsMatchingBoth()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "mf_both");
        var orders = harness.GetRequiredService<OrderStore>();

        await orders.InsertAsync(new Order { CustomerID = "ALFKI", EmployeeID = 1, ShipCity = "Berlin" });
        await orders.InsertAsync(new Order { CustomerID = "ALFKI", EmployeeID = 2, ShipCity = "Berlin" });
        await orders.InsertAsync(new Order { CustomerID = "BONAP", EmployeeID = 1, ShipCity = "Marseille" });

        var matched = await orders.SelectByCustomerAndEmployeeAsync("ALFKI", 1).ToListAsync();

        var only = Assert.Single(matched);
        Assert.Equal("ALFKI", only.CustomerID);
        Assert.Equal(1, only.EmployeeID);
        Assert.Equal("Berlin", only.ShipCity);
    }

    [SkippableFact]
    public async Task SelectByTwoFieldsReturnsEmptyWhenSecondFieldDoesNotMatch()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "mf_empty");
        var orders = harness.GetRequiredService<OrderStore>();

        await orders.InsertAsync(new Order { CustomerID = "ALFKI", EmployeeID = 1 });
        await orders.InsertAsync(new Order { CustomerID = "ALFKI", EmployeeID = 2 });

        var none = await orders.SelectByCustomerAndEmployeeAsync("ALFKI", 99).ToListAsync();

        Assert.Empty(none);
    }

    [SkippableFact]
    public async Task SingleColumnSelectByFieldStillWorks()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "mf_single");
        var orders = harness.GetRequiredService<OrderStore>();

        await orders.InsertAsync(new Order { CustomerID = "ALFKI", EmployeeID = 1 });
        await orders.InsertAsync(new Order { CustomerID = "ALFKI", EmployeeID = 2 });
        await orders.InsertAsync(new Order { CustomerID = "BONAP", EmployeeID = 3 });

        var alfkiOrders = await orders.SelectByCustomerAsync("ALFKI").ToListAsync();

        Assert.Equal(2, alfkiOrders.Count);
        Assert.All(alfkiOrders, o => Assert.Equal("ALFKI", o.CustomerID));
    }
}
