using Inquiry.Entities;
using Inquiry.Oracle.Tests.Fixtures;
using Inquiry.Stores;
using Oracle.ManagedDataAccess.Client;

namespace Inquiry.Oracle.Tests;

public readonly record struct OracleBusinessDate(DateOnly Value);

public sealed class OracleBusinessDateConverter : IInquiryValueConverter<OracleBusinessDate, DateOnly>
{
    public DateOnly ToProvider(OracleBusinessDate model) => model.Value;
    public OracleBusinessDate FromProvider(DateOnly provider) => new(provider);
}

[InquiryTable("ProviderReadItem")]
public sealed class ProviderReadItem
{
    [InquiryKey(IsGenerated = true)] public int Id { get; set; }
    [InquiryColumn] public int NumberValue { get; set; }
    [InquiryColumn] public bool Enabled { get; set; }
    [InquiryColumn] public Guid Token { get; set; }
    [InquiryColumn] public byte[] Payload { get; set; } = [];
    [InquiryColumn] public DateTime OccurredAt { get; set; }
    [InquiryColumn] public DateTimeOffset OffsetAt { get; set; }
    [InquiryColumn] public DateOnly EventDate { get; set; }
    [InquiryColumn] public TimeOnly EventTime { get; set; }
    [InquiryColumn(Converter = typeof(OracleBusinessDateConverter))]
    public OracleBusinessDate ConvertedDate { get; set; }
}

public partial class ProviderReadItemStore : InquiryStore<ProviderReadItem>
{
    [InquirySelectOneByKey]
    public partial Task<ProviderReadItem?> SelectByKeyAsync(int id, CancellationToken ct = default);
}

[Collection(OracleCollection.Name)]
public sealed class ProviderAwareMaterializerIntegrationTests
{
    private readonly OracleContainerFixture _fixture;
    public ProviderAwareMaterializerIntegrationTests(OracleContainerFixture fixture) => _fixture = fixture;

    private const string Ddl = """
        CREATE TABLE ProviderReadItem (
            Id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            NumberValue NUMBER(10) NOT NULL,
            Enabled NUMBER(1) NOT NULL,
            Token RAW(16) NOT NULL,
            Payload BLOB NOT NULL,
            OccurredAt TIMESTAMP NOT NULL,
            OffsetAt TIMESTAMP WITH TIME ZONE NOT NULL,
            EventDate DATE NOT NULL,
            EventTime INTERVAL DAY TO SECOND NOT NULL,
            ConvertedDate DATE NOT NULL)
        """;

    [SkippableFact]
    public async Task OrdinarySelectUsesProviderAwareReaders()
    {
        Skip.IfNot(_fixture.IsAvailable, _fixture.SkipReason);
        await using var harness = await OracleTestHarness.CreateFromDdlAsync(_fixture.AdminConnectionString, Ddl, "providerread");
        var store = harness.GetRequiredService<ProviderReadItemStore>();
        var token = Guid.NewGuid();
        var date = new DateOnly(2026, 7, 11);
        var item = new ProviderReadItem
        {
            NumberValue = 42,
            Enabled = true,
            Token = token,
            Payload = [1, 2, 3, 4],
            OccurredAt = new DateTime(2026, 7, 11, 12, 34, 56),
            OffsetAt = new DateTimeOffset(2026, 7, 11, 12, 34, 56, TimeSpan.FromHours(-4)),
            EventDate = date,
            EventTime = new TimeOnly(12, 34, 56),
            ConvertedDate = new OracleBusinessDate(date.AddDays(1)),
        };

        await using (var connection = new OracleConnection(harness.ConnectionString))
        {
            await connection.OpenAsync();
            await using var command = connection.CreateCommand();
            command.CommandText = $"""
                INSERT INTO ProviderReadItem
                    (NumberValue, Enabled, Token, Payload, OccurredAt, OffsetAt, EventDate, EventTime, ConvertedDate)
                VALUES
                    (42, 1, HEXTORAW('{Convert.ToHexString(token.ToByteArray())}'), HEXTORAW('01020304'),
                     TIMESTAMP '2026-07-11 12:34:56',
                     TO_TIMESTAMP_TZ('2026-07-11 12:34:56 -04:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
                     DATE '2026-07-11', INTERVAL '12:34:56' HOUR TO SECOND, DATE '2026-07-12')
                """;
            await command.ExecuteNonQueryAsync();
        }

        var selected = await store.SelectByKeyAsync(1);
        Assert.NotNull(selected);
        AssertItem(selected!, item);
    }

    private static void AssertItem(ProviderReadItem actual, ProviderReadItem expected)
    {
        Assert.Equal(expected.NumberValue, actual.NumberValue);
        Assert.Equal(expected.Enabled, actual.Enabled);
        Assert.Equal(expected.Token, actual.Token);
        Assert.Equal(expected.Payload, actual.Payload);
        Assert.Equal(expected.OccurredAt, actual.OccurredAt);
        Assert.Equal(expected.OffsetAt.UtcDateTime, actual.OffsetAt.UtcDateTime);
        Assert.Equal(expected.EventDate, actual.EventDate);
        Assert.Equal(expected.EventTime, actual.EventTime);
        Assert.Equal(expected.ConvertedDate, actual.ConvertedDate);
    }
}
